// Saturs — Ievas Jēkabsones vegānais 10 dienu ēdienreižu plāns.
// Avots: „vegans 10 dienu recepšu plāns" (Ievas oriģinālais dokuments).
//
// Divas oriģinālā kļūdas izlabotas ar nolūku, un tās ir jāzina:
//   1) 7. dienas pusdienās bija cepts lasis. Vegānā plānā tā ir kļūda, ne izvēle —
//      vietā ir cepts tofu ar tādu pašu lomu šķīvī.
//   2) Medus vietā visur ir kļavu sīrups. Daļa vegānu medu neēd, un produktā, ko pērk
//      tieši šā iemesla dēļ, tas nedrīkst būt jāizdomā pašam.
// Trešais labojums ir uzturvērtībā: oriģinālā vairākās dienās olbaltumvielu bija ap 40–55 g,
// un atsevišķās ēdienreizēs gandrīz nemaz. Te katrā ēdienreizē ir vismaz 11 g — pamatā no
// pākšaugiem, tofu, sēklām un sojas dzēriena.
import {
  philosophy, aboutLead, disclaimer, tips, adapt, howToUseSteps, swapsBase,
} from "../kopigais/kopigie-teksti.mjs";

export { allergens, sections, sectionOrder } from "../kopigais/kopigie-teksti.mjs";

export const meta = {
  title: "Vegānu recepšu un ēdienreižu plāns",
  subtitle: "10 dienām",
  author: "Ieva Jēkabsone",
  authorRole: "uztura konsultante",
  site: "ievajekabsone.lv",
};

export const product = {
  pdfName: "10-Dienu-Veganais-Uztura-Plans",
  cover: "vinka-fit-10-dienu-veganais-uztura-plans-vaks-luxury-01.webp",
  coverKicker: "Vegānais uztura ceļvedis",
  coverTitle: "Vegānu recepšu un<br>ēdienreižu plāns",
  coverTag: "Tikai augu valsts receptes ar izrēķinātām kalorijām, olbaltumvielām, iepirkumu sarakstu un pagatavošanas soļiem.",
  mealprepLead: "Sešas receptes plānā gatavo lielāku porciju. Daļu apēd uzreiz, otru — nākamajā dienā. Pākšaugu ēdieni nākamajā dienā parasti garšo pat labāk.",
  aboutPhoto: ["ieva-pasniedz-vakarinas-darzenu-kvinoja.webp", "Vakariņu šķīvis ar dārzeņiem un kvinoju — Ieva Jēkabsone, uztura konsultante"],
  prepPairs: [
    ["1. diena · pusdienas", "Tortilja ar pupiņām", "2. diena · otrās brokastis"],
    ["3. diena · vakariņas", "Ķirbja krēmzupa ar lēcām", "4. diena · otrās brokastis"],
    ["5. diena · pusdienas", "Dārzeņu sautējums ar sojas pupiņām", "6. diena · pusdienas"],
    ["7. diena · otrās brokastis", "Turku zirņu plācenīši", "8. diena · otrās brokastis"],
    ["8. diena · pusdienas", "Kartupeļu un pupiņu sautējums", "9. diena · pusdienas"],
    ["9. diena · vakariņas", "Lēcu zupa ar mangoldu", "10. diena · pusdienas"],
  ],
};

export const copy = {
  howToUseLead:
    "Šis ir tikai augu valsts plāns desmit dienām. Katrai dienai ir piecas ēdienreizes, izrēķinātas kalorijas un olbaltumvielas, un iepirkumu saraksts. Vegānā uzturā olbaltumvielas nesakrājas pašas — tāpēc katrā ēdienreizē te ir pākšaugi, tofu vai sēklas.",
  howToUseSteps,
  aboutLead,
  philosophy,
  forWhom:
    "Šis ir līdzsvarots vegānais plāns ar aptuveni 1400–1600 kcal dienā un aptuveni 70 g olbaltumvielu. Tas ir maigs sākums, ne ekstrēma diēta. Kalorijas aprēķinātas vidējām vajadzībām, neņemot vērā fizisko slodzi. Ja esi fiziski aktīvs, vīrietis vai vienkārši jūties izsalcis — pievieno porciju vai uzkodu. Klausies savu ķermeni.",
  adapt,
  disclaimer,
  tips: [
    ...tips,
    "B12 vitamīnu vegānā uzturā no ēdiena vien iegūt nevar. To lieto kā uztura bagātinātāju — par devu pajautā ārstam vai farmaceitam.",
  ],
  faq: [
    ["Vai vegānā uzturā pietiek olbaltumvielu?", "Pietiek, ja tās plāno. Šajā plānā katrā ēdienreizē ir pākšaugi, tofu, sēklas vai sojas dzēriens, un dienā sanāk ap 70 g."],
    ["Kāpēc sojas, ne auzu dzēriens?", "Sojas dzērienā ir apmēram 3,3 g olbaltumvielu uz 100 ml, auzu — ap 1 g. Putrā un smūtijā tā ir pusporcija olbaltumvielu, ko citādi zaudē."],
    ["Vai vajag B12?", "Jā. Tā ir vienīgā uzturviela, ko vegānā uzturā no ēdiena vien iegūt nevar. Pārējo — dzelzi, kalciju, omega-3 — plāns sedz, bet asinsanalīzes reizi gadā ir laba doma."],
    ["Kur šeit ir dzelzs?", "Lēcās, turku zirņos, sojas pupiņās, ķirbju sēklās un tumšajās lapās. Uzsūkšanos uzlabo C vitamīns, tāpēc gandrīz katrā maltītē ir arī paprika, tomāti vai citronu sula."],
    ["Vai produkti jāsver?", "Sākumā jā. Dārzeņus un putru ar laiku vari likt no acs, bet riekstus, sēklas, eļļu un vegāno sieru sver arī pēc tam — tajos ir visvairāk kaloriju uz gramu."],
    ["Kas notiek pēc 10 dienām?", "Turpini tos pašus principus: pākšaugi katrā dienā, pilngraudi, daudz dārzeņu un B12. Atkārto plānu vai veido savu."],
  ],
};

export const swaps = [
  ["Olbaltumvielu avoti", [
    ["Tofu", "Tempeh vai sojas gaļa", "Tempeh ir blīvāks un rūgtenāks — pirms cepšanas to var 10 min patvaicēt."],
    ["Lēcas", "Turku zirņi vai pupiņas", "Konservētās pirms lietošanas izskalo — tā atbrīvojies no liekā sāls."],
    ["Sojas pupiņas", "Melnās vai baltās pupiņas", "Sojas pupiņās ir visvairāk olbaltumvielu. Ja liec citas, porciju ņem par trešdaļu lielāku."],
    ["Turku zirņi", "Lēcas vai baltās pupiņas", "Sausie pirms vārīšanas jāizmērcē nakti — konservētie ir gatavi uzreiz."],
    ["Hummuss", "Sablenderēti turku zirņi ar tahini", "Veikala hummusā mēdz būt daudz eļļas — mājās gatavotajā tu izlem pats."],
    ["Ķirbju sēklas", "Saulespuķu sēklas vai kaņepju sēklas", "Kaņepju sēklās ir visvairāk olbaltumvielu un tās nav jāgrauzdē."],
  ]],
  ["Augu piena produkti", [
    ["Sojas dzēriens", "Zirņu vai kaņepju dzēriens", "Šiem trim ir visvairāk olbaltumvielu. Auzu un rīsu dzērienā to gandrīz nav."],
    ["Vegānais jogurts", "Sojas jogurts bez cukura", "Kokosriekstu jogurtā olbaltumvielu gandrīz nav — tas ir deserts, ne uzkoda."],
    ["Vegānais siers", "Uzturvielu raugs vai marinēts tofu", "Uzturvielu raugs dod to pašu sieram līdzīgo garšu, bet bez 23 g tauku."],
    ["Vegānais krējums", "Sablenderētas mērcētas Indijas rieksti", "Sauju riekstu mērcē stundu un sablenderē ar ūdeni — konsistence sanāk tāda pati."],
    ["Auzu kulinārijas krēms", "Kokosriekstu piens (vieglais)", "Kokosriekstu piens zupai dod saldenu piegaršu — tad citronu sulas vajag mazliet vairāk."],
    ["Augu krēmsiers", "Avokado ar citronu sulu", "Avokado uz maizes pilda to pašu lomu un dod arī kāliju."],
  ]],
  ...swapsBase,
];

export const dietSwaps = [
  ["Bez sojas", "Tofu un sojas pupiņas maini pret lēcām, turku zirņiem un seitanu. Sojas dzēriena vietā ņem zirņu vai kaņepju dzērienu — tajos olbaltumvielu ir tikpat."],
  ["Bez glutēna", "Kuskusu, grūbas, pilngraudu pastu un maizi maini pret rīsiem, griķiem, kvinoju un kukurūzas tortiljām."],
  ["Bez riekstiem", "Riekstus un zemesriekstu sviestu maini pret saulespuķu, ķirbju vai kaņepju sēklām un to sviestiem. Daudzumu paturi to pašu."],
];

// ---- 10 DIENAS ----
export const days = [
  {
    n: 1,
    batch: "Pusdienās gatavo divas tortiljas — vienu atstāj 2. dienas otrajām brokastīm.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra ar ogām", time: 10, a: ["glutens", "soja", "rieksti"],
        ing: "45 g auzu pārslas, 150 ml sojas dzēriens, 80 g svaigas ogas, 8 g rieksti.",
        steps: ["Auzu pārslas ar sojas dzērienu vāra 5–7 min, maisot.", "Virsū svaigas ogas un sadrupināti rieksti."] },
      { type: "otras", title: "Rīsi ar tofu un dārzeņiem", time: 20, a: ["soja"],
        ing: "120 g vārīti brūnie rīsi, 100 g tofu, 30 g šampinjoni, 30 g paprika, 5 g olīveļļa.",
        steps: ["Rīsus novāra.", "Tofu sagriež kubiciņos un cep olīveļļā, līdz malas kļūst brūnas — mīksts tofu garšo pēc nekā.", "Pievieno šampinjonus un papriku, sautē 5 min.", "Sajauc ar rīsiem."] },
      { type: "pusdienas", title: "Tortilja ar pupiņām", time: 15, portions: 2, a: ["glutens", "soja"],
        ing: "2 pilngraudu tortiljas, 200 g vārītas pupiņas, 40 g šampinjoni, 40 g spināti, 30 g vegānais siers.",
        steps: ["Pupiņas iepriekš izmērcē un novāra vai ņem konservētas un izskalo.", "Šampinjonus apcep, pievieno pupiņas un spinātus.", "Ar to pilda tortiljas, pārkaisa ar vegāno sieru.", "Saloka un uzsilda uz pannas. Vienu atliek 2. dienai."] },
      { type: "launags", title: "Vegānais jogurts ar augļiem un sēklām", time: 3, a: ["soja", "seklas"],
        ing: "150 g vegānais jogurts, 0,5 ābols, 0,5 banāns, 15 g ķirbju sēklas.",
        steps: ["Augļus sagriež, sajauc ar jogurtu, virsū ķirbju sēklas."] },
      { type: "vakarinas", title: "Salāti ar tofu un riekstiem", time: 12, a: ["soja", "rieksti"],
        ing: "60 g romiešu salāti, 30 g sēklu dīgsti, 20 g tomāti, 30 g avokado, 30 g paprika, 100 g tofu, 10 g grauzdēti rieksti, 5 g olīveļļa.",
        steps: ["Tofu sagriež un apcep uz sausas pannas.", "Dārzeņus un avokado sagriež.", "Sajauc ar dīgstiem, virsū tofu, rieksti un olīveļļa."] },
    ],
  },
  {
    n: 2,
    batch: "Otrajās brokastīs ēd vakar gatavoto tortilju.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar augu krēmsieru un avokado", time: 6, a: ["glutens", "seklas"],
        ing: "70 g rupjmaize, 15 g augu krēmsiers, 30 g avokado, 40 g gurķi, 15 g ķirbju sēklas.",
        steps: ["Maizi apziež ar augu krēmsieru, virsū avokado un gurķa šķēles, pārkaisa ar ķirbju sēklām."] },
      { type: "otras", title: "Tortilja ar pupiņām (no 1. dienas)", time: 5, from: "1/pusdienas", a: ["glutens", "soja"],
        ing: "Vakar pagatavotā otrā porcija.",
        steps: ["Uzsilda cepeškrāsnī vai uz pannas 5 min."] },
      { type: "pusdienas", title: "Salāti ar lēcām un ceptiem dārzeņiem", time: 30, a: [],
        ing: "50 g lēcas, 80 g spināti, 40 g tomāti, 40 g gurķi, 50 g sparģeļi, 50 g cukīni, 3 g olīveļļa.",
        steps: ["Lēcas novāra (~20 min) un atdzesē.", "Sparģeļus un cukīni cep 200 °C 15 min.", "Sajauc ar spinātiem, tomātiem un gurķi.", "Pārlej ar olīveļļu."] },
      { type: "launags", title: "Rīsu galetes ar zemesriekstu sviestu", time: 4, a: ["rieksti", "glutens", "soja"],
        ing: "2 pilngraudu rīsu galetes, 15 g zemesriekstu sviests, 150 g vegānais jogurts.",
        steps: ["Galetes apziež ar zemesriekstu sviestu, jogurts bļodiņā."] },
      { type: "vakarinas", title: "Banānu pankūkas", time: 15, a: ["glutens", "soja", "rieksti"],
        ing: "0,5 banāns, 40 g pilngraudu milti, 100 ml sojas dzēriens, 10 g zemesriekstu sviests, 3 g olīveļļa.",
        steps: ["Banānu saspaida ar dakšiņu.", "Sajauc ar miltiem un sojas dzērienu, atstāj 5 min.", "Cep uz iesmērētas pannas 2–3 min katrā pusē.", "Virsū zemesriekstu sviests."] },
    ],
  },
  {
    n: 3,
    batch: "Čia pudiņu samaisi jau iepriekšējā vakarā. Vakariņās gatavo krēmzupu divām reizēm.",
    meals: [
      { type: "brokastis", title: "Čia pudiņš ar ogām", time: 5, a: ["seklas", "soja"],
        ing: "25 g čia sēklas, 200 ml sojas dzēriens, 150 g vegānais jogurts, 50 g svaigas ogas.",
        steps: ["Čia sēklas, sojas dzērienu un jogurtu samaisa.", "Ledusskapī vismaz 20 min, labāk visu nakti — sēklas uzbriest un masa kļūst bieza.", "Virsū svaigas ogas."] },
      { type: "otras", title: "Rīsu galetes ar zemesriekstu sviestu", time: 4, a: ["rieksti", "glutens", "soja"],
        ing: "2 pilngraudu rīsu galetes, 15 g zemesriekstu sviests, 150 g vegānais jogurts.",
        steps: ["Galetes apziež ar zemesriekstu sviestu, pasniedz ar jogurtu."] },
      { type: "pusdienas", title: "Kuskuss ar tofu un dārzeņiem", time: 20, a: ["glutens", "soja"],
        ing: "50 g kuskuss, 100 g tofu, 20 g burkāni, 30 g paprika, 30 g spināti, 5 g olīveļļa.",
        steps: ["Kuskusu aplej ar verdošu ūdeni un apsedz 5 min.", "Tofu sagriež un apcep olīveļļā.", "Pievieno burkānu un papriku, sautē 5 min.", "Sajauc ar kuskusu un spinātiem."] },
      { type: "launags", title: "Kliju maize ar hummusu", time: 5, a: ["glutens", "seklas"],
        ing: "50 g kliju maize, 60 g hummuss, 8 g grauzdētas saulespuķu sēklas, 1 persiks.",
        steps: ["Maizi apziež ar hummusu, pārkaisa ar saulespuķu sēklām.", "Persiks."] },
      { type: "vakarinas", title: "Ķirbja krēmzupa ar lēcām", time: 30, portions: 2, a: ["seklas"],
        ing: "200 g ķirbis, 60 g sīpoli, 10 g ķiploki, 80 g burkāni, 100 g kartupeļi, 70 g sarkanās lēcas, 30 g auzu kulinārijas krēms, pipari, sāls.",
        serve: "10 g ķirbju sēklas.",
        steps: ["Sīpolu un ķiplokus apcep.", "Pievieno ķirbi, burkānu, kartupeli un ūdeni.", "Sarkanās lēcas izskalo un pievieno — tās izvārās mīkstas un sablenderējas gludi.", "Vāra ~20 min, pievieno auzu krēmu un sablenderē.", "Katrai porcijai virsū 20 g ķirbju sēklu. Pusi atliek 4. dienai."] },
    ],
  },
  {
    n: 4,
    batch: "Otrajās brokastīs ēd vakar gatavoto krēmzupu.",
    meals: [
      { type: "brokastis", title: "Piecu graudu pārslu putra", time: 10, a: ["glutens", "soja", "rieksti"],
        ing: "40 g piecu graudu pārslas, 150 ml sojas dzēriens, 80 g svaigas ogas, 8 g rieksti.",
        steps: ["Pārslas ar sojas dzērienu vāra 5 min.", "Virsū ogas un sadrupināti rieksti."] },
      { type: "otras", title: "Ķirbja krēmzupa (no 3. dienas)", time: 5, from: "3/vakarinas", a: ["seklas"],
        ing: "Vakar gatavotā krēmzupa, 10 g ķirbju sēklas.",
        steps: ["Zupu uzsilda, virsū uzkaisa ķirbju sēklas."] },
      { type: "pusdienas", title: "Turku zirņi ar tvaicētiem dārzeņiem", time: 25, a: [],
        ing: "60 g turku zirņi, 30 g brokolis, 30 g cukīni, 5 g olīveļļa.",
        steps: ["Turku zirņus izmērcē nakti un novāra (~40 min) vai ņem konservētus.", "Brokoļus un cukīni tvaicē 8 min.", "Sajauc un pārlej ar olīveļļu."] },
      { type: "launags", title: "Vegānais jogurts ar banānu un šokolādi", time: 3, a: ["soja", "seklas"],
        ing: "150 g vegānais jogurts, 10 g kļavu sīrups, 0,5 banāns, 15 g ķirbju sēklas, 2 gabaliņi tumšās šokolādes.",
        steps: ["Banānu sagriež un sajauc ar jogurtu un kļavu sīrupu, virsū ķirbju sēklas un sarīvēta šokolāde."] },
      { type: "vakarinas", title: "Svaigie salāti ar grauzdiņiem", time: 15, a: ["glutens", "seklas"],
        ing: "100 g rukola, 30 g gurķi, 30 g tomāti, 30 g paprika, 40 g rupjmaizes grauzdiņi, 15 g grauzdētas saulespuķu sēklas, 60 g tofu.",
        steps: ["Rupjmaizi sagriež kubiciņos un cep 180 °C 10 min bez taukvielām.", "Dārzeņus sagriež un sajauc ar rukolu.", "Virsū grauzdiņi, sēklas un olīveļļa."] },
    ],
  },
  {
    n: 5,
    batch: "Pusdienās gatavo sautējumu divām reizēm — pusi atstāj 6. dienai.",
    meals: [
      { type: "brokastis", title: "Rudzu polārmaize ar krēmsieru un avokado", time: 6, a: ["glutens", "seklas"],
        ing: "80 g rudzu polārmaize, 15 g augu krēmsiers, 30 g tomāti, 30 g avokado, 12 g ķirbju sēklas, baziliks.",
        steps: ["Maizi apziež ar augu krēmsieru, virsū avokado, tomāti un baziliks, pārkaisa ar ķirbju sēklām."] },
      { type: "otras", title: "Griķi ar sautētiem dārzeņiem", time: 20, a: [],
        ing: "50 g griķi, 60 g tofu, 30 g brokolis, 60 g sviesta pupiņas, 30 g šampinjoni.",
        steps: ["Griķus novāra (~15 min).", "Dārzeņus sautē olīveļļā 8 min.", "Sajauc kopā."] },
      { type: "pusdienas", title: "Dārzeņu sautējums ar sojas pupiņām", time: 45, portions: 2, a: ["soja"],
        ing: "200 g kartupeļi, 100 g burkāni, 80 g sīpoli, 80 g kālis, 80 g baltais kāposts, 10 g ķiploki, 40 g sojas pupiņas, 5 g olīveļļa, pipari, sāls.",
        steps: ["Sojas pupiņas izmērcē nakti un novāra (~50 min).", "Sīpolu un ķiplokus apcep olīveļļā.", "Pievieno sagrieztus dārzeņus un mazliet ūdens.", "Sautē 25 min, pievieno pupiņas. Sāli pievieno gatavam. Pusi atliek 6. dienai."] },
      { type: "launags", title: "Bietes ar maizi un sēklām", time: 5, a: ["glutens", "seklas"],
        ing: "100 g vārītas bietes, 100 g vegānais jogurts, 50 g kliju maize, 15 g saulespuķu sēklas.",
        steps: ["Bietes sarīvē un sajauc ar vegāno jogurtu, pasniedz ar maizes šķēli un uzkaisītām saulespuķu sēklām."] },
      { type: "vakarinas", title: "Svaigie salāti ar riekstiem", time: 15, a: ["glutens", "rieksti"],
        ing: "100 g rukola, 30 g gurķi, 30 g tomāti, 30 g paprika, 40 g rupjmaizes grauzdiņi, 10 g grauzdēti rieksti, 60 g tofu.",
        steps: ["Rupjmaizi sagriež kubiciņos un cep 180 °C 10 min.", "Dārzeņus sagriež un sajauc ar rukolu.", "Virsū grauzdiņi, rieksti un olīveļļa."] },
    ],
  },
  {
    n: 6,
    batch: "Pusdienās ēd vakar gatavoto dārzeņu sautējumu.",
    meals: [
      { type: "brokastis", title: "Smūtija bļoda ar auzu pārslām", time: 8, a: ["soja", "glutens", "rieksti"],
        ing: "0,5 banāns, 30 g svaigas ogas, 150 ml sojas dzēriens, 40 g spināti, 35 g auzu pārslas, 8 g rieksti.",
        steps: ["Banānu, ogas, sojas dzērienu un spinātus sablenderē, ielej bļodā, virsū grauzdētas auzu pārslas un rieksti."] },
      { type: "otras", title: "Rīsu galetes ar zemesriekstu sviestu", time: 4, a: ["rieksti", "glutens", "soja"],
        ing: "2 pilngraudu rīsu galetes, 15 g zemesriekstu sviests, 150 g vegānais jogurts.",
        steps: ["Galetes apziež ar zemesriekstu sviestu, pasniedz ar jogurtu."] },
      { type: "pusdienas", title: "Dārzeņu sautējums (no 5. dienas)", time: 5, from: "5/pusdienas", a: ["soja"],
        ing: "Vakar gatavotais sautējums, pētersīļi.",
        steps: ["Sautējumu uzsilda, pārkaisa ar svaigiem pētersīļiem."] },
      { type: "launags", title: "Burkānu salāti ar sēklām un maizi", time: 8, a: ["glutens", "seklas"],
        ing: "100 g rīvēti burkāni, 15 g grauzdētas ķirbju sēklas, 50 g kliju maize, 100 g vegānais jogurts.",
        steps: ["Burkānus sarīvē un pārlej ar olīveļļu, pārkaisa ar ķirbju sēklām, pasniedz ar maizes šķēli."] },
      { type: "vakarinas", title: "Pasta ar dārzeņiem un pesto", time: 20, a: ["glutens"],
        ing: "60 g pilngraudu pasta, 80 g tofu, 30 g šampinjoni, 30 g paprika, 40 g brokolis, 5 g pesto.",
        steps: ["Pastu novāra.", "Tofu sagriež kubiciņos un apcep, pievieno dārzeņus un sautē 8 min.", "Sajauc ar pastu un pesto."] },
    ],
  },
  {
    n: 7,
    batch: "Otrajās brokastīs gatavo turku zirņu plācenīšus divām reizēm — pusi atstāj 8. dienai.",
    meals: [
      { type: "brokastis", title: "Piecu graudu pārslu putra", time: 10, a: ["glutens", "soja", "rieksti"],
        ing: "40 g piecu graudu pārslas, 150 ml sojas dzēriens, 80 g svaigas ogas, 8 g rieksti.",
        steps: ["Pārslas ar sojas dzērienu vāra 5 min.", "Virsū ogas un sadrupināti rieksti."] },
      { type: "otras", title: "Turku zirņu un cukīni plācenīši", time: 30, portions: 2, a: ["glutens"],
        ing: "400 g cukīni, 100 g burkāni, 90 g turku zirņi, 40 g sīpoli, 20 g kukurūzas ciete, 25 g pilngraudu milti, 6 g olīveļļa, dilles, sāls.",
        steps: ["Turku zirņus izmērcē nakti un novāra vai ņem konservētus un izskalo.", "Cukīni un burkānus sarīvē, pieber šķipsnu sāls un atstāj 10 min suloties.", "Sulu izspiež — bez tā plācenīši izjūk pannā.", "Turku zirņus saberž ar dakšiņu līdz rupjai masai un sajauc ar dārzeņiem, cieti, miltiem, sīpolu un dillēm.", "Cep uz pannas 3 min katrā pusē. Pusi atliek 8. dienai."] },
      { type: "pusdienas", title: "Biezenis ar ceptu tofu un bietēm", time: 30, a: ["soja"],
        ing: "100 g kartupeļi, 100 g ziedkāposts, 40 ml sojas dzēriens, 120 g tofu, 100 g vārītas bietes, 15 g vegānais krējums, pipari.",
        steps: ["Kartupeļus un ziedkāpostu novāra un saspiež biezenī ar sojas dzērienu.", "Tofu sagriež šķēlēs un cep cepeškrāsnī 200 °C 20 min bez taukvielām.", "Bietes sarīvē un sajauc ar vegāno krējumu.", "Visu pasniedz uz viena šķīvja."] },
      { type: "launags", title: "Vegānais jogurts ar augļiem un sēklām", time: 3, a: ["soja", "seklas"],
        ing: "150 g vegānais jogurts, 10 g kļavu sīrups, 0,5 banāns, 0,5 apelsīns, 15 g ķirbju sēklas.",
        steps: ["Augļus sagriež, sajauc ar jogurtu un kļavu sīrupu, virsū sēklas."] },
      { type: "vakarinas", title: "Svaigie salāti ar hummusa maizi", time: 12, a: ["glutens", "seklas"],
        ing: "80 g romiešu salāti, 40 g tomāti, 40 g gurķi, 40 g paprika, 50 g kliju maize, 40 g hummuss, 8 g grauzdētas ķirbju sēklas, 5 g olīveļļa, baziliks.",
        steps: ["Maizi apziež ar hummusu un pārkaisa ar grauzdētām ķirbju sēklām.", "Dārzeņus sagriež un sajauc ar bazilika lapām.", "Salātus pārlej ar olīveļļu un pasniedz kopā ar maizi."] },
    ],
  },
  {
    n: 8,
    batch: "Pusdienās gatavo sautējumu divām reizēm — pusi atstāj 9. dienai.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar augu krēmsieru un avokado", time: 6, a: ["glutens", "seklas"],
        ing: "70 g rupjmaize, 15 g augu krēmsiers, 30 g avokado, 40 g gurķi, 15 g ķirbju sēklas.",
        steps: ["Maizi apziež ar augu krēmsieru, virsū avokado un gurķa šķēles, pārkaisa ar ķirbju sēklām."] },
      { type: "otras", title: "Turku zirņu plācenīši (no 7. dienas)", time: 5, from: "7/otras", a: ["glutens"],
        ing: "Vakar gatavotie plācenīši, pētersīļi.",
        steps: ["Plācenīšus uzsilda uz pannas vai ēd aukstus."] },
      { type: "pusdienas", title: "Kartupeļu un pupiņu sautējums", time: 35, portions: 2, a: [],
        ing: "200 g kartupeļi, 300 g zaļās pupiņas, 180 g vārītas pupiņas, 40 g sīpoli, 200 g nomizoti tomāti, 10 g olīveļļa, pipari, sāls.",
        steps: ["Sīpolu apcep olīveļļā.", "Pievieno kartupeļus, tomātus un mazliet ūdens, sautē 15 min.", "Pievieno zaļās pupiņas un vārītās pupiņas, sautē vēl 10 min.", "Sāli pievieno gatavam. Pusi atliek 9. dienai."] },
      { type: "launags", title: "Vegānais jogurts ar augļiem un sēklām", time: 3, a: ["soja", "seklas"],
        ing: "150 g vegānais jogurts, 10 g kļavu sīrups, 0,5 banāns, 15 g ķirbju sēklas.",
        steps: ["Augļus sagriež, sajauc ar jogurtu, virsū sēklas."] },
      { type: "vakarinas", title: "Lēcas ar tvaicētiem dārzeņiem", time: 30, a: [],
        ing: "45 g lēcas, 50 g ziedkāposts, 50 g cukīni, 30 g burkāni, 30 g paprika, 5 g olīveļļa, sāls.",
        steps: ["Lēcas novāra (~20 min).", "Dārzeņus tvaicē 8–10 min.", "Sajauc, pārlej ar olīveļļu, sāli pievieno gatavam."] },
    ],
  },
  {
    n: 9,
    batch: "Vakariņās gatavo lēcu zupu divām reizēm — pusi atstāj 10. dienas pusdienām.",
    meals: [
      { type: "brokastis", title: "Rudzu polārmaize ar krēmsieru un avokado", time: 6, a: ["glutens", "seklas"],
        ing: "80 g rudzu polārmaize, 15 g augu krēmsiers, 30 g tomāti, 30 g avokado, 12 g ķirbju sēklas, baziliks.",
        steps: ["Maizi apziež ar augu krēmsieru, virsū avokado, tomāti un baziliks, pārkaisa ar ķirbju sēklām."] },
      { type: "otras", title: "Vegānais jogurts ar augļiem un riekstiem", time: 3, a: ["soja", "rieksti"],
        ing: "150 g vegānais jogurts, 0,5 ābols, 20 g ķirbju sēklas.",
        steps: ["Augļus sagriež, sajauc ar jogurtu, virsū sadrupināti rieksti."] },
      { type: "pusdienas", title: "Kartupeļu un pupiņu sautējums (no 8. dienas)", time: 5, from: "8/pusdienas", a: [],
        ing: "Vakar gatavotais sautējums, pētersīļi.",
        steps: ["Sautējumu uzsilda, pārkaisa ar svaigiem pētersīļiem."] },
      { type: "launags", title: "Rīsu galetes ar zemesriekstu sviestu un ogām", time: 4, a: ["rieksti", "glutens", "soja"],
        ing: "2 pilngraudu rīsu galetes, 18 g zemesriekstu sviests, 100 g vegānais jogurts, 1 apelsīns.",
        steps: ["Galetes apziež ar zemesriekstu sviestu, jogurts bļodiņā.", "Apelsīns."] },
      { type: "vakarinas", title: "Lēcu zupa ar mangoldu", time: 35, portions: 2, a: ["glutens"],
        ing: "90 g lēcas, 50 g sīpoli, 400 g mangolds, 5 g olīveļļa, ūdens, lauru lapa, romiešu ķimenes, citronu sula, pipari, sāls.",
        serve: "20 g rupjmaizes grauzdiņi.",
        steps: ["Sīpolu apcep olīveļļā ar romiešu ķimenēm.", "Pievieno lēcas, ūdeni un lauru lapu, vāra 25 min.", "Pievieno sagrieztu mangoldu un vāra vēl 5 min.", "Sablenderē, pievieno citronu sulu — tā uzlabo dzelzs uzsūkšanos.", "Katrai porcijai virsū grauzdiņi. Pusi atliek 10. dienai."] },
    ],
  },
  {
    n: 10,
    batch: "Pusdienās ēd vakar gatavoto lēcu zupu.",
    meals: [
      { type: "brokastis", title: "Vraps ar tofu un pesto", time: 12, a: ["glutens", "soja"],
        ing: "1 pilngraudu tortilja, 8 g pesto, 50 g rukola, 30 g gurķi, 30 g tomāti, 100 g tofu, 10 g vegānais krējums, dilles.",
        steps: ["Tofu sagriež sloksnītēs un apcep.", "Tortilju apziež ar pesto un vegāno krējumu.", "Liek rukolu, dārzeņus un tofu, saloka."] },
      { type: "otras", title: "Bietes ar maizi un sēklām", time: 5, a: ["glutens", "seklas"],
        ing: "100 g vārītas bietes, 10 g vegānais krējums, 50 g rupjmaize, 12 g saulespuķu sēklas, 100 g vegānais jogurts.",
        steps: ["Bietes sarīvē un sajauc ar vegāno krējumu, pasniedz ar maizes šķēli un sēklām, jogurts bļodiņā."] },
      { type: "pusdienas", title: "Lēcu zupa (no 9. dienas)", time: 5, from: "9/vakarinas", a: ["glutens"],
        ing: "Vakar gatavotā lēcu zupa, 20 g rupjmaizes grauzdiņi.",
        steps: ["Zupu uzsilda, virsū grauzdiņi."] },
      { type: "launags", title: "Vegānais jogurts ar augļiem un riekstiem", time: 3, a: ["soja", "rieksti"],
        ing: "150 g vegānais jogurts, 10 g kļavu sīrups, 1 persiks, 15 g ķirbju sēklas.",
        steps: ["Augļus sagriež, sajauc ar jogurtu, virsū rieksti."] },
      { type: "vakarinas", title: "Grūbas ar dārzeņiem", time: 40, a: ["glutens", "seklas"],
        ing: "50 g grūbas, 30 g burkāni, 30 g paprika, 30 g šampinjoni, 30 g cukīni, 20 g sīpoli, 5 g ķiploki, 15 g ķirbju sēklas, 5 g olīveļļa, pētersīļi, pipari.",
        steps: ["Grūbas novāra (~30 min).", "Dārzeņus sagriež un sautē olīveļļā 10 min.", "Sajauc ar grūbām, virsū grauzdētas ķirbju sēklas."] },
    ],
  },
];

// ---- IEPIRKUMU DATI ----
export const catalog = {
  "Pilngraudu auzu pārslas": ["Graudi un putraimi", "1 paka (500 g)"],
  "Piecu graudu pārslas": ["Graudi un putraimi", "1 paka"],
  "Kuskuss": ["Graudi un putraimi", "1 maza paka"],
  "Griķi": ["Graudi un putraimi", "1 maza paka"],
  "Grūbas": ["Graudi un putraimi", "1 maza paka"],
  "Brūnie rīsi": ["Graudi un putraimi", "1 maza paka"],
  "Lēcas": ["Graudi un putraimi", "1 paka"],
  "Sarkanās lēcas": ["Graudi un putraimi", "1 maza paka"],
  "Turku zirņi": ["Graudi un putraimi", "1 paka vai 2 bundžas"],
  "Hummuss": ["Olbaltums", "~150 g (bez pievienotas eļļas)"],
  "Sojas pupiņas": ["Graudi un putraimi", "1 maza paka"],
  "Vārītas pupiņas": ["Graudi un putraimi", "3 bundžas vai 1 paka sausu"],
  "Pilngraudu pasta": ["Graudi un putraimi", "1 paka"],
  "Pilngraudu milti": ["Graudi un putraimi", "1 paka"],
  "Kukurūzas ciete": ["Graudi un putraimi", "1 maza paka"],
  "Čia sēklas": ["Graudi un putraimi", "1 maza paka"],
  "Rupjmaize": ["Maize", "kvalitatīva, mazāk sāls"],
  "Kliju maize": ["Maize", "1 kukulis"],
  "Rudzu polārmaize": ["Maize", "1 paka"],
  "Rīsu galetes": ["Maize", "1 paka (pilngraudu)"],
  "Pilngraudu tortilja": ["Maize", "1 paka"],
  "Sojas dzēriens": ["Piena produkti", "1,5 l (nesaldināts)"],
  "Vegānais jogurts": ["Piena produkti", "~1,5 kg (sojas, bez cukura)"],
  "Vegānais siers": ["Piena produkti", "1 paka"],
  "Vegānais krējums": ["Piena produkti", "1 maza paka"],
  "Augu krēmsiers": ["Piena produkti", "1 maza paka"],
  "Auzu kulinārijas krēms": ["Piena produkti", "1 maza paka"],
  "Tofu": ["Olbaltums", "~800 g"],
  "Spināti": ["Dārzeņi un zaļumi", "2 pakas"],
  "Rukola": ["Dārzeņi un zaļumi", "2 pakas"],
  "Romiešu salāti": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Mangolds vai kalē": ["Dārzeņi un zaļumi", "~400 g"],
  "Gurķi": ["Dārzeņi un zaļumi", "2 gab"],
  "Tomāti": ["Dārzeņi un zaļumi", "~450 g svaigu"],
  "Paprika": ["Dārzeņi un zaļumi", "~4 gab"],
  "Burkāni": ["Dārzeņi un zaļumi", "~700 g"],
  "Cukīni": ["Dārzeņi un zaļumi", "~700 g"],
  "Ziedkāposts": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Brokolis": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Sparģeļi": ["Dārzeņi un zaļumi", "1 maza saite"],
  "Šampinjoni": ["Dārzeņi un zaļumi", "1 paka"],
  "Sīpoli": ["Dārzeņi un zaļumi", "~4 gab"],
  "Ķiploki": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Ķirbis": ["Dārzeņi un zaļumi", "1 gabals"],
  "Kartupeļi": ["Dārzeņi un zaļumi", "~1 kg"],
  "Kālis (kolrābis)": ["Dārzeņi un zaļumi", "1 gab"],
  "Baltais kāposts": ["Dārzeņi un zaļumi", "1 mazs gabals"],
  "Zaļās pupiņas": ["Dārzeņi un zaļumi", "~400 g (var saldētas)"],
  "Sviesta pupiņas": ["Dārzeņi un zaļumi", "1 maza paka (var saldētas)"],
  "Bietes": ["Dārzeņi un zaļumi", "3 vārītas bietes"],
  "Sēklu dīgsti": ["Dārzeņi un zaļumi", "1 maza paka"],
  "Avokado": ["Dārzeņi un zaļumi", "~3 gab"],
  "Dilles": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Pētersīļi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Baziliks": ["Dārzeņi un zaļumi", "1 podiņš"],
  "Ābols": ["Augļi", "~4 gab"],
  "Apelsīns": ["Augļi", "~2 gab"],
  "Banāns": ["Augļi", "~5 gab"],
  "Persiki": ["Augļi", "~3 gab"],
  "Svaigas ogas": ["Augļi", "~600 g (var saldētas)"],
  "Zemesriekstu sviests": ["Rieksti un sēklas", "1 burka"],
  "Rieksti (mandeles, valrieksti)": ["Rieksti un sēklas", "1 paka"],
  "Ķirbju sēklas": ["Rieksti un sēklas", "1 paka"],
  "Saulespuķu sēklas": ["Rieksti un sēklas", "1 paka"],
  "Olīveļļa": ["Eļļas, garšvielas, citi", "Extra Virgin, 1 pudele"],
  "Kļavu sīrups": ["Eļļas, garšvielas, citi", "1 pudelīte"],
  "Pesto": ["Eļļas, garšvielas, citi", "1 maza burka (vegāns)"],
  "Tumšā šokolāde": ["Eļļas, garšvielas, citi", "1 tāfelīte (≥70 %)"],
};

// Produkti, kas labi stāv 10 dienas -> pērc VIENREIZ pirmajā iepirkumā.
export const pantry = new Set([
  "Pilngraudu auzu pārslas", "Piecu graudu pārslas", "Kuskuss", "Griķi", "Grūbas",
  "Brūnie rīsi", "Lēcas", "Sarkanās lēcas", "Turku zirņi", "Sojas pupiņas",
  "Vārītas pupiņas", "Pilngraudu pasta", "Pilngraudu milti", "Kukurūzas ciete",
  "Čia sēklas", "Rīsu galetes", "Pilngraudu tortilja", "Sojas dzēriens",
  "Zemesriekstu sviests", "Rieksti (mandeles, valrieksti)", "Ķirbju sēklas",
  "Saulespuķu sēklas", "Olīveļļa", "Kļavu sīrups", "Pesto", "Tumšā šokolāde",
  "Burkāni", "Sīpoli", "Ķiploki", "Ķirbis", "Kartupeļi", "Kālis (kolrābis)",
  "Baltais kāposts", "Zaļās pupiņas", "Sviesta pupiņas", "Bietes", "Ābols", "Apelsīns",
]);
