// Saturs — Ievas Jēkabsones vasaras 10 dienu ēdienreižu plāns.
// Avots: „Vasaras veselīgo recepšu plāns" (Ievas oriģinālais dokuments).
// Oriģinālā daļā dienu bija četras ēdienreizes un uzkodas bez olbaltumvielām; te tas ir
// salikts tajā pašā formā, kas pamatplānā — piecas ēdienreizes, katrā vismaz 11 g
// olbaltumvielu. Skaitļus rēķina kopigais/uzturvertibas.mjs, ne roka.
import {
  philosophy, aboutLead, disclaimer, tips, adapt, howToUseSteps, swapsBase,
} from "../kopigais/kopigie-teksti.mjs";

export { allergens, sections, sectionOrder } from "../kopigais/kopigie-teksti.mjs";

export const meta = {
  title: "Vasarīgu recepšu un ēdienreižu plāns",
  subtitle: "10 dienām",
  author: "Ieva Jēkabsone",
  authorRole: "uztura konsultante",
  site: "ievajekabsone.lv",
};

export const product = {
  pdfName: "10-Dienu-Vasaras-Uztura-Plans",
  cover: "vinka-fit-10-dienu-vasaras-uztura-plans-vaks-luxury-02.webp",
  coverKicker: "Vasaras uztura ceļvedis",
  coverTitle: "Vasarīgu recepšu un<br>ēdienreižu plāns",
  coverTag: "Sezonas dārzeņi un ogas, aukstās zupas un salāti. Ar izrēķinātām kalorijām, iepirkumu sarakstu un pagatavošanas soļiem.",
  mealprepLead: "Trīs receptes plānā gatavo lielāku porciju. Daļu apēd uzreiz, otru — nākamajā dienā. Vasarā tas nozīmē arī mazāk laika pie karstas plīts.",
  aboutPhoto: ["ieva-ogas-biezpiens-balta-boda.webp", "Svaigas ogas ar biezpienu baltā bļodā — vasaras uzkoda no plāna"],
  prepPairs: [
    ["3. diena · vakariņas", "Cukīni plācenīši", "4. diena · brokastis"],
    ["7. diena · vakariņas", "Pildīti cukīni", "8. diena · launags"],
    ["9. diena · launags", "Banānu un mango saldējums", "10. diena · launags"],
  ],
};

export const copy = {
  howToUseLead:
    "Šis ir desmit vasaras dienu plāns. Katrai dienai ir piecas ēdienreizes, izrēķinātas kalorijas un iepirkumu saraksts. Receptēs ir sezonas dārzeņi un ogas, un liela daļa maltīšu ir aukstas — plīts vasarā jāieslēdz pēc iespējas retāk.",
  howToUseSteps,
  aboutLead,
  philosophy,
  forWhom:
    "Šis ir līdzsvarots plāns ar aptuveni 1400–1550 kcal dienā. Tas ir maigs sākums, ne ekstrēma diēta. Kalorijas aprēķinātas vidējām vajadzībām, neņemot vērā fizisko slodzi. Ja esi fiziski aktīvs, vīrietis vai vienkārši jūties izsalcis — pievieno porciju vai uzkodu. Klausies savu ķermeni.",
  adapt,
  disclaimer,
  tips: [...tips.slice(0, 7), "Olas izvēlies no brīvībā augušām vistām un eko saimniecības, ja iespējams.", tips[7]],
  faq: [
    ["Ar ko šis plāns atšķiras no pamatplāna?", "Produktu izvēle ir vasaras: svaigas ogas, cukīni, tomāti, gurķi, aukstās zupas un salāti. Princips ir tas pats."],
    ["Vai ogas drīkst būt saldētas?", "Jā. Saldētās ogas ir tikpat vērtīgas un ārpus sezonas lētākas. Atlaidina tās ledusskapī, ne uz letes."],
    ["Vai varu ēst dārza dārzeņus, kas nav sarakstā?", "Vari. Vasarā tas pat ir mērķis. Dārzeņus maini gandrīz brīvi — svarīgi, lai šķīvī paliek olbaltumvielu porcija."],
    ["Vai produkti jāsver?", "Sākumā jā. Dārzeņus un putru ar laiku vari likt no acs, bet riekstus, sēklas, eļļu un sierus sver arī pēc tam — tajos ir visvairāk kaloriju uz gramu."],
    ["Kāpēc uzkodās vienmēr ir biezpiens vai jogurts?", "Auglis viens pats nesātina un pēc stundas tu jau meklē nākamo uzkodu. Olbaltumviela to maina."],
    ["Kas notiek pēc 10 dienām?", "Turpini tos pašus principus: dārzeņi, olbaltums, pilngraudi un ūdens. Atkārto plānu vai veido savu."],
  ],
};

export const swaps = [
  ["Gaļa, zivs, olas", [
    ["Vistas fileja", "Tītara fileja, liesa cūkgaļas karbonāde", "Gatavošanas laiks līdzīgs. Tītars ir sausāks — necep pārāk ilgi."],
    ["Baltā zivs (menca, heks)", "Forele, lasis vai vista", "Lasis ir taukaināks. Ja liec to vietā, porciju ņem mazliet mazāku."],
    ["Forele", "Lasis vai skumbrija", "Abas ir treknās zivis ar to pašu lomu maltītē."],
    ["Tuncis savā sulā", "Vārīta vista vai baltā zivs", "Ņem tunci savā sulā, ne eļļā — eļļā tas ir gandrīz divreiz kalorijām blīvāks."],
    ["Garneles", "Vista, tofu vai baltā zivs", "Garneles gatavojas 3 minūtēs, vista — apmēram 10. Rēķinies ar laiku."],
    ["Olas", "Tofu (kultenī), biezpiens", "Olu vietā tofu ņem apmēram pusotru reizi vairāk pēc svara."],
  ]],
  ["Piena produkti", [
    ["Vājpiens", "Auzu vai mandeļu dzēriens", "Izvēlies bez pievienota cukura — saldinātajā ir līdz 7 g cukura uz 100 ml."],
    ["Biezpiens", "Grieķu jogurts vai skyr", "Ņem nesaldinātu. Saldinātajā mēdz būt divreiz vairāk cukura."],
    ["Grieķu jogurts", "Biezpiens ar karoti kefīra", "Konsistence sanāks biezāka — kefīru pievieno pamazām."],
    ["Kefīrs", "Naturāls jogurts vai paniņas", "Aukstajai zupai der arī paniņas — tās ir vēl mazliet skābākas."],
    ["Kazas siers", "Feta vai mocarella", "Feta ir daudz sāļāka — tad ēdienam sāli vairs nepievieno."],
    ["Liess siers", "Mocarella vai jauns siers", "Vasarā salātos labāk der mīkstie sieri, ne cietie."],
  ]],
  ...swapsBase,
];

export const dietSwaps = [
  ["Bez laktozes", "Piena produktus maini pret bezlaktozes vai augu versijām. Aukstajai zupai ņem augu jogurtu ar ūdeni."],
  ["Bez glutēna", "Kuskusu, kliju maizi un pilngraudu pastu maini pret rīsiem, griķiem vai kvinoju."],
  ["Veģetārietim", "Gaļu un zivi maini pret tofu, pupiņām, lēcām un olām. Olbaltumvielu daudzumu paturi to pašu."],
];

// ---- 10 DIENAS ----
export const days = [
  {
    n: 1,
    batch: "Vakarā izvāri olas un bietes aukstajai zupai — no rīta tās jau būs atdzisušas.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar biezpienu un olu", time: 8, a: ["piens", "glutens", "olas"],
        ing: "70 g rupjmaize, 60 g biezpiens (0,5 %), 60 g grieķu jogurts (0 %), 1 ola, dilles.",
        steps: ["Olu novāra 8 min.", "Biezpienu sajauc ar jogurtu un dillēm, uzziež uz maizes, virsū pusē griezta ola."] },
      { type: "otras", title: "Ābols ar biezpienu", time: 3, a: ["piens"],
        ing: "1 ābols, 80 g biezpiens (0,5 %).",
        steps: ["Ābolu sagriež šķēlītēs, pasniedz ar biezpienu."] },
      { type: "pusdienas", title: "Ziedkāposta pica", time: 35, a: ["piens", "olas", "glutens"],
        ing: "100 g ziedkāposts, 80 g liess siers (10 %), 1 ola, 15 g pilngraudu milti, 20 g tomātu pasta, 20 g šampinjoni, 20 g tomāti, 10 g sīpoli, 10 g spināti.",
        steps: ["Ziedkāpostu sarīvē vai sasmalcina blenderī un 5 min tvaicē.", "Nospiež lieko ūdeni cauri tīram dvielim — citādi pamatne nesacietēs.", "Sajauc ar olu, pusi siera, miltiem un garšvielām.", "Izklāj uz papīra un cep 200 °C 20 min.", "Uzziež tomātu pastu, virsū dārzeņus un atlikušo sieru, cep vēl 10 min."] },
      { type: "launags", title: "Rīsu galetes ar biezpienu un ogām", time: 4, a: ["rieksti", "piens", "glutens"],
        ing: "2 pilngraudu rīsu galetes, 10 g zemesriekstu sviests, 60 g biezpiens (0,5 %), 30 g svaigas ogas.",
        steps: ["Galetes apziež ar zemesriekstu sviestu un biezpienu, virsū svaigas ogas."] },
      { type: "vakarinas", title: "Aukstā biešu zupa", time: 15, a: ["piens", "olas"],
        ing: "100 g vārītas bietes, 2 olas, 30 g redīsi, 40 g gurķi, dilles, 300 ml kefīrs (2,5 %).",
        steps: ["Bietes sarīvē, gurķi un redīsus sagriež.", "Olas novāra 8 min un sagriež.", "Visu pārlej ar aukstu kefīru.", "Pievieno dilles un ļauj 10 min ledusskapī ievilkties."] },
    ],
  },
  {
    n: 2,
    batch: "Saldo kartupeli pusdienu salātiem izcep jau no rīta — atdzisis tas garšo labāk.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu pankūka ar ogām", time: 15, a: ["glutens", "olas", "rieksti"],
        ing: "50 g auzu pārslas, 1 ola, 0,5 banāns, 7 g olīveļļa, 10 g zemesriekstu sviests, 30 g svaigas ogas.",
        steps: ["Auzu pārslas sasmalcina blenderī ar banānu un olu.", "Masu 5 min atstāj — pārslas uzsūc šķidrumu un pankūka neizjūk.", "Cep uz iesmērētas pannas 3 min katrā pusē.", "Virsū zemesriekstu sviests un ogas."] },
      { type: "otras", title: "Ogas ar jogurtu un riekstiem", time: 3, a: ["piens", "rieksti"],
        ing: "100 g svaigas ogas, 100 g grieķu jogurts (0 %), 10 g rieksti.",
        steps: ["Jogurtu liek bļodā, virsū ogas un sadrupināti rieksti."] },
      { type: "pusdienas", title: "Kazas siera un saldā kartupeļa salāti", time: 30, a: ["piens", "rieksti"],
        ing: "100 g saldais kartupelis, 60 g spināti, 30 g svaigas ogas, 40 g mīksts kazas siers, 7 g olīveļļa, 10 g valrieksti.",
        steps: ["Saldo kartupeli sagriež gabaliņos un cep 200 °C 25 min bez taukvielām.", "Atdzesē — karsts kartupelis salātos savāra spinātus.", "Sajauc ar spinātiem un ogām.", "Virsū kazas siers, valrieksti un olīveļļa."] },
      { type: "launags", title: "Persiks ar biezpienu", time: 3, a: ["piens"],
        ing: "1 persiks, 100 g biezpiens (0,5 %).",
        steps: ["Persiku sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Baltā zivs ar vasaras dārzeņiem", time: 30, a: ["zivs"],
        ing: "150 g baltās zivs fileja, 70 g paprika, 70 g cukīni, 70 g brokolis, 50 g saldais kartupelis, 7 g olīveļļa, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200 °C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs un pipari.", "Cep 20–25 min, sāli pievieno gatavam."] },
    ],
  },
  {
    n: 3,
    batch: "Vakariņās gatavo cukīni plācenīšus divām reizēm — pusi atstāj 4. dienas brokastīm.",
    meals: [
      { type: "brokastis", title: "Olu kultenis ar vasaras salātiem", time: 12, a: ["olas", "piens"],
        ing: "2 olas, 20 g spināti, 30 ml vājpiens (0,5 %), 5 g olīveļļa, 40 g romiešu salāti, 30 g tomāti, 30 g paprika, 30 g gurķi, 30 g liess siers (10 %).",
        steps: ["Olas sakuļ ar vājpienu.", "Uz siltas pannas olīveļļā cep kultenī, pievieno spinātus.", "Salātu dārzeņus sagriež un sajauc ar sieru.", "Pasniedz kopā."] },
      { type: "otras", title: "Ogas ar jogurtu", time: 3, a: ["piens"],
        ing: "100 g svaigas ogas, 120 g grieķu jogurts (0 %).",
        steps: ["Jogurtu liek bļodā, virsū ogas."] },
      { type: "pusdienas", title: "Kvinoja ar vistu un dārzeņiem", time: 25, a: [],
        ing: "70 g kvinoja, 80 g vistas fileja, 20 g burkāni, 30 g paprika, 30 g spināti, 5 g olīveļļa.",
        steps: ["Kvinoju pirms vārīšanas izskalo aukstā ūdenī — tā nozūd rūgtenā garša.", "Vāra 12–15 min.", "Vistas fileju sagriež un apcep olīveļļā ar burkānu un papriku.", "Sajauc ar kvinoju un spinātiem."] },
      { type: "launags", title: "Ābols ar biezpienu", time: 3, a: ["piens"],
        ing: "1 ābols, 80 g biezpiens (0,5 %).",
        steps: ["Ābolu sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Cukīni plācenīši", time: 25, portions: 2, a: ["olas", "glutens"],
        ing: "300 g cukīni, 30 g sīpoli, 40 g spināti, 2 olas, 100 g pilngraudu milti, 10 g olīveļļa, dilles, sāls.",
        serve: "40 g grieķu jogurts (0 %).",
        steps: ["Cukīni sarīvē, pieber šķipsnu sāls un atstāj 10 min suloties.", "Sulu izspiež — bez tā plācenīši izjūk pannā.", "Sajauc ar olām, miltiem, sīpolu, spinātiem un dillēm.", "Cep uz pannas 3 min katrā pusē.", "Pusi atliek 4. dienas brokastīm. Pasniedz ar jogurtu."] },
    ],
  },
  {
    n: 4,
    batch: "Brokastīs ēd vakar pagatavotos cukīni plācenīšus.",
    meals: [
      { type: "brokastis", title: "Cukīni plācenīši (no 3. dienas)", time: 5, from: "3/vakarinas", a: ["olas", "glutens", "piens"],
        ing: "Vakar pagatavotie plācenīši, 40 g grieķu jogurts (0 %).",
        steps: ["Plācenīšus uzsilda uz pannas vai ēd aukstus, pasniedz ar jogurtu."] },
      { type: "otras", title: "Persiks ar biezpienu", time: 3, a: ["piens"],
        ing: "1 persiks, 100 g biezpiens (0,5 %).",
        steps: ["Persiku sagriež, pasniedz ar biezpienu."] },
      { type: "pusdienas", title: "Pilngraudu pasta ar tofu un dārzeņiem", time: 20, a: ["glutens", "soja", "piens"],
        ing: "60 g pilngraudu pasta, 60 g tofu, 30 g šampinjoni, 30 g paprika, 40 g brokolis, 30 g liess siers (10 %), 7 g olīveļļa.",
        steps: ["Pastu novāra.", "Tofu sagriež kubiciņos un apcep olīveļļā, līdz malas kļūst brūnas.", "Pievieno dārzeņus un sautē 5 min.", "Sajauc ar pastu, virsū rīvēts siers."] },
      { type: "launags", title: "Jogurts ar šokolādi un mandelēm", time: 3, a: ["piens", "rieksti"],
        ing: "120 g grieķu jogurts (0 %), 2 gabaliņi tumšās šokolādes, 10 g mandeles.",
        steps: ["Šokolādi un mandeles sarīvē vai sakapā, uzber uz jogurta."] },
      { type: "vakarinas", title: "Aukstā biešu zupa", time: 15, a: ["piens", "olas"],
        ing: "100 g vārītas bietes, 2 olas, 30 g redīsi, 40 g gurķi, dilles, 300 ml kefīrs (2,5 %).",
        steps: ["Bietes sarīvē, gurķi un redīsus sagriež.", "Olas novāra un sagriež.", "Pārlej ar aukstu kefīru un pievieno dilles."] },
    ],
  },
  {
    n: 5,
    batch: "Šodien nekas nav jāpagatavo iepriekš — visas maltītes ir svaigas.",
    meals: [
      { type: "brokastis", title: "Smūtija bļoda ar ogām", time: 8, a: ["piens", "glutens"],
        ing: "1 banāns, 30 g svaigas ogas, 40 ml vājpiens (0,5 %), 100 g grieķu jogurts (0 %), 40 g spināti, 40 g auzu pārslas.",
        steps: ["Banānu, ogas, vājpienu, jogurtu un spinātus sablenderē, ielej bļodā, virsū grauzdētas auzu pārslas."] },
      { type: "otras", title: "Ābols ar biezpienu un mandelēm", time: 3, a: ["piens", "rieksti"],
        ing: "1 ābols, 60 g biezpiens (0,5 %), 10 g mandeles.",
        steps: ["Ābolu sagriež, pasniedz ar biezpienu un mandelēm."] },
      { type: "pusdienas", title: "Tunča salāti ar maizi", time: 12, a: ["zivs", "olas", "glutens"],
        ing: "40 g rukola, 30 g tomāti, 30 g gurķi, 30 g paprika, 100 g tuncis savā sulā, 1 ola, 10 g sīpoli, 7 g olīveļļa, 40 g rupjmaize.",
        steps: ["Olu novāra 8 min.", "Tunci nokāš no sulas.", "Dārzeņus sagriež, sajauc ar rukolu un tunci.", "Pārlej ar olīveļļu, virsū pusē griezta ola. Pasniedz ar maizes šķēli."] },
      { type: "launags", title: "Ogas ar jogurtu", time: 3, a: ["piens"],
        ing: "100 g svaigas ogas, 120 g grieķu jogurts (0 %).",
        steps: ["Jogurtu liek bļodā, virsū ogas."] },
      { type: "vakarinas", title: "Forele ar dārzeņiem", time: 30, a: ["zivs"],
        ing: "120 g foreles fileja, 80 g baklažāns, 80 g ziedkāposts, 50 g paprika, 60 g saldais kartupelis, 5 g olīveļļa.",
        steps: ["Cepeškrāsni uzsilda līdz 200 °C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū forele, sāls, pipari.", "Cep ~20 min."] },
    ],
  },
  {
    n: 6,
    batch: "Vistas fileju vakariņu salātiem izcep kopā ar pusdienu lēcām — plīts jāieslēdz vienreiz.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar biezpienu un avokado", time: 8, a: ["piens", "glutens"],
        ing: "60 g rupjmaize, 60 g biezpiens (0,5 %), 40 g grieķu jogurts (0 %), 30 g spināti, 40 g avokado, 30 g gurķi, 30 g tomāti, 5 g olīveļļa.",
        steps: ["Biezpienu sajauc ar jogurtu, uzziež uz maizes, virsū avokado šķēles.", "Salāti no spinātiem, gurķa un tomāta ar olīveļļu."] },
      { type: "otras", title: "Ogas ar jogurtu", time: 3, a: ["piens"],
        ing: "100 g svaigas ogas, 120 g grieķu jogurts (0 %).",
        steps: ["Jogurtu liek bļodā, virsū ogas."] },
      { type: "pusdienas", title: "Lēcas ar tvaicētiem dārzeņiem", time: 30, a: [],
        ing: "100 g lēcas, 50 g ziedkāposts, 50 g cukīni, 30 g burkāni, 30 g paprika, 7 g olīveļļa, sāls.",
        steps: ["Lēcas novāra (~20 min).", "Dārzeņus tvaicē 8–10 min.", "Sajauc, pārlej ar olīveļļu, sāli pievieno gatavam."] },
      { type: "launags", title: "Persiks ar biezpienu", time: 3, a: ["piens"],
        ing: "1 persiks, 80 g biezpiens (0,5 %).",
        steps: ["Persiku sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Kartupeļu salāti ar vistu", time: 25, a: ["olas", "piens"],
        ing: "100 g vārīti kartupeļi, 60 g vistas fileja, 2 olas, 15 g puravs, 20 g grieķu jogurts (0 %), 5 g sinepes, zaļumi.",
        steps: ["Kartupeļus novāra un atdzesē — atdzisušos tie salātos neizjūk.", "Vistas fileju izcep un sagriež gabaliņos.", "Olas novāra un sagriež.", "Jogurtu sajauc ar sinepēm un pārlej salātiem."] },
    ],
  },
  {
    n: 7,
    batch: "Vakariņās gatavo divas pildītas cukīni pusītes — vienu atstāj 8. dienas launagam.",
    meals: [
      { type: "brokastis", title: "Banānu pankūkas ar ogām", time: 15, a: ["piens", "olas", "glutens"],
        ing: "1 banāns, 60 g biezpiens (0,5 %), 1 ola, 40 g pilngraudu milti, 5 g olīveļļa, 80 g svaigas ogas.",
        steps: ["Banānu saspaida ar dakšiņu.", "Sajauc ar biezpienu, olu un miltiem.", "Cep uz iesmērētas pannas 2–3 min katrā pusē.", "Virsū svaigas ogas."] },
      { type: "otras", title: "Jogurts ar ogām un riekstiem", time: 3, a: ["piens", "rieksti"],
        ing: "100 g grieķu jogurts (0 %), 30 g svaigas ogas, 10 g rieksti.",
        steps: ["Jogurtu liek bļodā, virsū ogas un sadrupināti rieksti."] },
      { type: "pusdienas", title: "Vista kokosriekstu pienā ar kuskusu", time: 25, a: ["glutens"],
        ing: "100 g vistas fileja, 20 g burkāni, 30 g paprika, 40 g kukurūza, 40 g kokosriekstu piens, 50 g kuskuss, garšvielas.",
        steps: ["Kuskusu aplej ar verdošu ūdeni un apsedz 5 min.", "Vistas fileju sagriež un apcep.", "Pievieno dārzeņus un kokosriekstu pienu, sautē 10 min.", "Pasniedz ar kuskusu."] },
      { type: "launags", title: "Ābols ar biezpienu", time: 3, a: ["piens"],
        ing: "1 ābols, 80 g biezpiens (0,5 %).",
        steps: ["Ābolu sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Pildīti cukīni ar vistu", time: 40, portions: 2, a: ["piens"],
        ing: "400 g cukīni, 40 g šampinjoni, 120 g vistas fileja, 20 g sīpoli, 5 g ķiploki, 70 g liess siers (10 %), 7 g olīveļļa, pipari, sāls.",
        serve: "15 g grieķu jogurts (0 %), zaļumi.",
        steps: ["Cukīni pārgriež uz pusēm un vidu izgrebj.", "Vistas fileju, sīpolu, ķiplokus un šampinjonus sagriež un apcep olīveļļā.", "Ar to pilda cukīni puses, pārkaisa ar sieru.", "Cep 200 °C 25 min.", "Vienu pusi atliek 8. dienai. Pasniedz ar jogurtu un zaļumiem."] },
    ],
  },
  {
    n: 8,
    batch: "Launagā ēd vakar gatavoto pildīto cukīni.",
    meals: [
      { type: "brokastis", title: "Kliju maize ar olām", time: 12, a: ["olas", "glutens", "piens"],
        ing: "2 olas, 70 g kliju maize, 20 g krēmsiers, 60 g gurķi, zaļumi.",
        steps: ["Olas novāra 8 min.", "Maizi apziež ar krēmsieru.", "Virsū olas šķēles, gurķis un zaļumi."] },
      { type: "otras", title: "Ogas ar jogurtu un riekstiem", time: 3, a: ["piens", "rieksti"],
        ing: "100 g svaigas ogas, 100 g grieķu jogurts (0 %), 10 g rieksti.",
        steps: ["Jogurtu liek bļodā, virsū ogas un rieksti."] },
      { type: "pusdienas", title: "Brūnie rīsi ar dārzeņiem", time: 30, a: ["piens"],
        ing: "200 g vārīti brūnie rīsi, 30 g burkāni, 30 g paprika, 30 g šampinjoni, 30 g cukīni, 20 g sīpoli, 5 g ķiploki, 30 g liess siers (10 %), 7 g olīveļļa, pētersīļi, pipari.",
        steps: ["Rīsus novāra.", "Dārzeņus sagriež un sautē olīveļļā 10 min.", "Sajauc ar rīsiem, virsū rīvēts siers un pētersīļi."] },
      { type: "launags", title: "Pildīti cukīni (no 7. dienas)", time: 5, from: "7/vakarinas", a: ["piens"],
        ing: "Vakar gatavotā pildītā cukīni puse, 15 g grieķu jogurts (0 %).",
        steps: ["Cukīni uzsilda, virsū jogurts un zaļumi."] },
      { type: "vakarinas", title: "Baltā zivs ar cukīni un brokoļiem", time: 30, a: ["zivs"],
        ing: "150 g baltās zivs fileja, 150 g saldais kartupelis, 80 g cukīni, 80 g brokolis, 7 g olīveļļa, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200 °C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs un pipari.", "Cep 20–25 min."] },
    ],
  },
  {
    n: 9,
    batch: "Launagā gatavo saldējumu divām reizēm — pusi ieliec saldētavā 10. dienai.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra ar banānu", time: 10, a: ["piens", "glutens", "rieksti"],
        ing: "60 g auzu pārslas, 100 ml vājpiens (0,5 %), 0,5 banāns, 10 g zemesriekstu sviests.",
        steps: ["Auzu pārslas ar vājpienu vāra 5–7 min, maisot.", "Virsū sagriezts banāns un zemesriekstu sviests."] },
      { type: "otras", title: "Ābols ar biezpienu", time: 3, a: ["piens"],
        ing: "1 ābols, 80 g biezpiens (0,5 %).",
        steps: ["Ābolu sagriež, pasniedz ar biezpienu."] },
      { type: "pusdienas", title: "Turku zirņi ar tofu", time: 25, a: ["soja"],
        ing: "70 g turku zirņi, 70 g tofu, 20 g burkāni, 30 g paprika, 30 g spināti, 7 g olīveļļa.",
        steps: ["Turku zirņus izmērcē nakti un novāra.", "Tofu sagriež un apcep olīveļļā.", "Pievieno burkānu un papriku, sautē 5 min.", "Sajauc ar zirņiem un spinātiem."] },
      { type: "launags", title: "Banānu un mango saldējums", time: 10, portions: 2, a: ["piens"],
        ing: "1 banāns, 100 g mango, 40 g proteīna pulveris, 60 ml vājpiens (0,5 %).",
        steps: ["Banānu un mango sagriež un sasaldē (vai ņem jau saldētus).", "Sablenderē kopā ar proteīna pulveri un pienu.", "Liek traukā saldētavā un ik pa 20 min apmaisa — tā masa sasalst vienmērīgi.", "Pusi atliek 10. dienai."] },
      { type: "vakarinas", title: "Salāti ar garnelēm", time: 12, a: ["juras", "piens"],
        ing: "60 g romiešu salāti, 30 g tomāti, 30 g gurķi, 30 g paprika, 100 g garneles, 7 g olīveļļa, baziliks, 200 ml kefīrs (2,5 %).",
        steps: ["Garneles apcep olīveļļā 3–4 min.", "Dārzeņus sagriež un sajauc.", "Virsū garneles un baziliks. Pasniedz ar glāzi kefīra."] },
    ],
  },
  {
    n: 10,
    batch: "Launagā ēd vakar gatavoto saldējumu.",
    meals: [
      { type: "brokastis", title: "Olu kultenis ar maizi", time: 10, a: ["olas", "piens", "glutens"],
        ing: "2 olas, 50 ml vājpiens (0,5 %), 40 g spināti, 5 g olīveļļa, 40 g gurķi, 40 g rupjmaize.",
        steps: ["Olas sakuļ ar vājpienu.", "Cep olīveļļā, pievieno spinātus.", "Pasniedz ar maizes šķēli un svaigu gurķi."] },
      { type: "otras", title: "Ogas ar jogurtu", time: 3, a: ["piens"],
        ing: "100 g svaigas ogas, 120 g grieķu jogurts (0 %).",
        steps: ["Jogurtu liek bļodā, virsū ogas."] },
      { type: "pusdienas", title: "Griķi ar tītaru un dārzeņiem", time: 30, a: [],
        ing: "70 g griķi, 100 g tītara fileja, 30 g brokolis, 60 g sviesta pupiņas, 30 g šampinjoni, 7 g olīveļļa.",
        steps: ["Griķus novāra (~15 min).", "Tītara fileju sagriež un apcep olīveļļā.", "Pievieno brokoļus, pupiņas un šampinjonus, sautē 8 min.", "Sajauc ar griķiem."] },
      { type: "launags", title: "Banānu un mango saldējums (no 9. dienas)", time: 3, from: "9/launags", a: ["piens"],
        ing: "Vakar gatavotais saldējums.",
        steps: ["Saldējumu 5 min patur istabas temperatūrā, tad apēd."] },
      { type: "vakarinas", title: "Forele ar dārzeņiem", time: 30, a: ["zivs"],
        ing: "120 g foreles fileja, 80 g baklažāns, 80 g ziedkāposts, 50 g paprika, 60 g saldais kartupelis, 5 g olīveļļa.",
        steps: ["Cepeškrāsni uzsilda līdz 200 °C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū forele, sāls, pipari.", "Cep ~20 min."] },
    ],
  },
];

// ---- IEPIRKUMU DATI ----
export const catalog = {
  "Pilngraudu auzu pārslas": ["Graudi un putraimi", "1 paka (500 g)"],
  "Kvinoja": ["Graudi un putraimi", "1 maza paka"],
  "Kuskuss": ["Graudi un putraimi", "1 maza paka"],
  "Griķi": ["Graudi un putraimi", "1 paka"],
  "Brūnie rīsi": ["Graudi un putraimi", "1 paka"],
  "Lēcas": ["Graudi un putraimi", "1 paka"],
  "Turku zirņi": ["Graudi un putraimi", "1 maza paka"],
  "Pilngraudu pasta": ["Graudi un putraimi", "1 paka"],
  "Pilngraudu milti": ["Graudi un putraimi", "1 paka"],
  "Rupjmaize": ["Maize", "kvalitatīva, mazāk sāls"],
  "Kliju maize": ["Maize", "1 maza kukulis"],
  "Rīsu galetes": ["Maize", "1 paka (pilngraudu)"],
  "Vājpiens": ["Piena produkti", "0,5 l (0,5 %)"],
  "Biezpiens": ["Piena produkti", "~900 g (0,5 %)"],
  "Grieķu jogurts": ["Piena produkti", "~1 kg (0 %)"],
  "Kefīrs": ["Piena produkti", "1 l (2,5 %)"],
  "Liess siers": ["Piena produkti", "1 gabals (10 %)"],
  "Kazas siers": ["Piena produkti", "1 maza paka (mīkstais)"],
  "Krēmsiers": ["Piena produkti", "1 maza paka (light)"],
  "Olas": ["Olas", "~20 gab"],
  "Tofu": ["Olbaltums", "1 paka"],
  "Proteīna pulveris": ["Olbaltums", "pēc izvēles, var izlaist"],
  "Vistas fileja": ["Gaļa un zivs", "~400 g"],
  "Tītara fileja": ["Gaļa un zivs", "~100 g"],
  "Baltā zivs": ["Gaļa un zivs", "~300 g (heks/menca)"],
  "Forele": ["Gaļa un zivs", "~250 g"],
  "Garneles": ["Gaļa un zivs", "~100 g"],
  "Tuncis savā sulā": ["Gaļa un zivs", "1 bundža"],
  "Spināti": ["Dārzeņi un zaļumi", "2 pakas"],
  "Rukola": ["Dārzeņi un zaļumi", "1 paka"],
  "Romiešu salāti": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Gurķi": ["Dārzeņi un zaļumi", "2–3 gab"],
  "Tomāti": ["Dārzeņi un zaļumi", "~300 g"],
  "Paprika": ["Dārzeņi un zaļumi", "~5 gab"],
  "Burkāni": ["Dārzeņi un zaļumi", "~300 g"],
  "Cukīni": ["Dārzeņi un zaļumi", "~1,2 kg"],
  "Ziedkāposts": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Brokolis": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Baklažāns": ["Dārzeņi un zaļumi", "1 gab"],
  "Šampinjoni": ["Dārzeņi un zaļumi", "1 paka"],
  "Sīpoli": ["Dārzeņi un zaļumi", "~2 gab"],
  "Ķiploki": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Puravs": ["Dārzeņi un zaļumi", "1 kāts"],
  "Redīsi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Kartupeļi": ["Dārzeņi un zaļumi", "~100 g"],
  "Saldais kartupelis": ["Dārzeņi un zaļumi", "~450 g"],
  "Bietes": ["Dārzeņi un zaļumi", "2 vārītas bietes"],
  "Kukurūza": ["Dārzeņi un zaļumi", "1 maza bundža"],
  "Sviesta pupiņas": ["Dārzeņi un zaļumi", "1 maza paka (var saldētas)"],
  "Avokado": ["Dārzeņi un zaļumi", "1 gab"],
  "Zaļumi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Dilles": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Pētersīļi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Baziliks": ["Dārzeņi un zaļumi", "1 podiņš"],
  "Ābols": ["Augļi", "~5 gab"],
  "Banāns": ["Augļi", "~4 gab"],
  "Persiki": ["Augļi", "~3 gab"],
  "Mango": ["Augļi", "1 gab"],
  "Svaigas ogas": ["Augļi", "~900 g (var saldētas)"],
  "Zemesriekstu sviests": ["Rieksti un sēklas", "1 burka"],
  "Rieksti (mandeles, valrieksti)": ["Rieksti un sēklas", "1 paka"],
  "Olīveļļa": ["Eļļas, garšvielas, citi", "Extra Virgin, 1 pudele"],
  "Tomātu pasta": ["Eļļas, garšvielas, citi", "1 maza bundža"],
  "Kokosriekstu piens": ["Eļļas, garšvielas, citi", "1 bundža (vieglais)"],
  "Sinepes": ["Eļļas, garšvielas, citi", "1 burciņa"],
  "Tumšā šokolāde": ["Eļļas, garšvielas, citi", "1 tāfelīte (≥70 %)"],
};

// Produkti, kas labi stāv 10 dienas -> pērc VIENREIZ pirmajā iepirkumā.
export const pantry = new Set([
  "Pilngraudu auzu pārslas", "Kvinoja", "Kuskuss", "Griķi", "Brūnie rīsi", "Lēcas",
  "Turku zirņi", "Pilngraudu pasta", "Pilngraudu milti", "Rīsu galetes",
  "Zemesriekstu sviests", "Rieksti (mandeles, valrieksti)", "Olīveļļa", "Tomātu pasta",
  "Kokosriekstu piens", "Sinepes", "Tumšā šokolāde", "Proteīna pulveris", "Tuncis savā sulā",
  "Kukurūza", "Sviesta pupiņas",
  "Burkāni", "Sīpoli", "Ķiploki", "Kartupeļi", "Saldais kartupelis", "Bietes",
  "Ābols", "Mango",
  "Olas",
]);
