// Saturs — Ievas Jēkabsones 10 dienu ēdienreižu plāns
// Visi teksti latviešu valodā, UTF-8. Skaitļi = Ievas oriģinālie (pārbaudāmi ar Ievu).

export const meta = {
  title: "Veselīgu recepšu un ēdienreižu plāns",
  subtitle: "10 dienām",
  author: "Ieva Jēkabsone",
  authorRole: "uztura konsultante",
  site: "ievajekabsone.lv",
};

export const copy = {
  howToUseLead:
    "Šis plāns ir desmit dienu sākums, ne mūža diēta. Katrai dienai ir piecas ēdienreizes, izrēķinātas kalorijas un iepirkumu saraksts. Ej secīgi vai izvēlies dienas, kas patīk.",
  howToUseSteps: [
    "Izlasi vispārīgos ieteikumus.",
    "Saliec nedēļas iepirkumu sarakstu un nopērc pamatkrājumu.",
    "Apskati meal-prep karti — daļu ēdienu pagatavo vienreiz, apēd divreiz.",
    "Seko dienām. Ēd mierīgi, bez telefona.",
    "Katru vakaru pieraksti pašsajūtu.",
  ],
  aboutLead:
    "Esmu Ieva Jēkabsone, uztura konsultante. Ticu, ka uzturu maina mazi soļi, ne aizliegumi. Negribu, lai tu badojies vai skaiti katru kumosu. Gribu, lai tu saproti, kāpēc ēd tā, kā ēd, un lai tas der tavai ikdienai.",
  philosophy: [
    ["Pielāgošana, ne aizliegumi", "Neviens produkts nav aizliegts. Svarīgs ir kopējais."],
    ["Ilgtspēja, ne ātrums", "Lēni veidotas pārmaiņas paliek. Ātras — pazūd."],
    ["Sīkumi skaitās", "Glāze ūdens, viena maltīte, viens solis. No tā veidojas rezultāts."],
    ["Godīgums", "Ja kaut ko nezinu, tā arī pateikšu. Bez tukšiem solījumiem."],
  ],
  forWhom:
    "Šis ir līdzsvarots plāns ar aptuveni 1300–1600 kcal dienā. Tas ir maigs sākums, ne ekstrēma diēta. Kalorijas aprēķinātas vidējām vajadzībām, neņemot vērā fizisko slodzi. Ja esi fiziski aktīvs, vīrietis vai vienkārši jūties izsalcis — pievieno porciju vai uzkodu. Klausies savu ķermeni.",
  adapt: [
    ["Izsalcis?", "Palielini olbaltumu un dārzeņu porciju, ne ogļhidrātus."],
    ["Par daudz ēdiena?", "Samazini putraimu vai maizes daudzumu."],
    ["Nepatīk produkts?", "Skaties aizstāšanas tabulu — gandrīz visu var nomainīt."],
    ["Aktīva diena?", "Pievieno uzkodu: olu, sauju riekstu vai augli."],
  ],
  disclaimer:
    "Šis plāns ir vispārīgs un izglītojošs. Tā nav medicīniska ārstēšana vai individuāls uztura plāns. Ja esi grūtniece, baro bērnu ar krūti, lieto medikamentus vai tev ir veselības stāvoklis (piemēram, diabēts, vairogdziedzera saslimšana vai alerģijas), pirms maini ēšanu konsultējies ar ārstu vai uztura speciālistu. Kaloriju un uzturvielu skaitļi ir aptuveni.",
  closing:
    "Paldies, ka izvēlējies šo plānu. Atceries — tu nemaini visu uzreiz. Tu maini vienu maltīti, vienu dienu, vienu sīkumu. Tieši tā veidojas paliekoša pārmaiņa. Lai izdodas!",
  tips: [
    "Ūdeni dzer vismaz 2 l dienā. Tēja un nesaldināti dzērieni skaitās, bet vismaz 1,5 l lai ir tīrs ūdens.",
    "Samazini sāli. Pievieno to jau gatavam ēdienam un izmanto rupjo sāli.",
    "Dzērieniem nepievieno cukuru. Ja vajag, lieto stēviju vai eritritolu.",
    "Izvairies no konservētiem, sālītiem, marinētiem un žāvētiem produktiem.",
    "Termiskai apstrādei izmanto tikai auksta spieduma (Extra Virgin) olīveļļu.",
    "Salātiem pievieno riekstu, avokado vai linsēklu eļļu. Tās nedrīkst karsēt.",
    "Garšvielas lieto pēc savas gaumes, bet bez pievienota sāls.",
    "Olas izvēlies no brīvībā augušām vistām un eko saimniecības, ja iespējams.",
    "Ēdot neskaties TV un nelieto telefonu. Koncentrējies uz ēšanu.",
  ],
  faq: [
    ["Vai šis ir svara zaudēšanas plāns?", "Tas ir līdzsvarots reset. Daudziem aptuveni 1400 kcal nozīmē vieglu deficītu, bet rezultāts atkarīgs no tavām vajadzībām un aktivitātes."],
    ["Vai drīkstu mainīt receptes?", "Jā. Tas ir mērķis. Pielāgo plānu savai garšai un produktiem, kas pieejami."],
    ["Cik daudz ūdens jādzer?", "Vismaz 2 l dienā. No tā vismaz 1,5 l lai ir tīrs ūdens."],
    ["Vai produkti jāsver?", "Sākumā tas palīdz saprast porcijas. Ar laiku redzēsi tās no acs un svari vairs nav vajadzīgi."],
    ["Ko darīt ar sāli un cukuru?", "Sāli pievieno gatavam ēdienam un maz. Dzērieniem cukuru nepievieno."],
    ["Kas notiek pēc 10 dienām?", "Turpini tos pašus principus: dārzeņi, olbaltums, pilngraudi un ūdens. Atkārto plānu vai veido savu."],
  ],
};

// Alergēnu leģenda
export const allergens = {
  piens: "Piens",
  olas: "Olas",
  zivs: "Zivs",
  juras: "Jūras veltes",
  rieksti: "Rieksti",
  glutens: "Glutēns",
  soja: "Soja",
};

// Aizstāšanas tabula
export const swaps = [
  ["Baltā zivs, forele, lasis", "Vista, tītars (vai otrādi)"],
  ["Garneles", "Vista, tofu vai baltā zivs"],
  ["Vājpiens", "Augu dzēriens (auzu, mandeļu) bez cukura"],
  ["Biezpiens", "Grieķu jogurts vai augu jogurts"],
  ["Kefīrs", "Naturāls jogurts vai augu jogurts"],
  ["Liess siers", "Fetas siers (mazāk) vai augu siers"],
  ["Lēcas", "Pupiņas vai turku zirņi"],
  ["Grūbas, kuskuss", "Brūnie rīsi, griķi vai kvinoja"],
  ["Zemesriekstu sviests", "Mandeļu sviests vai tahini"],
  ["Rupjmaize", "Pilngraudu maize bez rauga"],
  ["Banāns", "Bumbieris vai ābols (mazāk cukura)"],
  ["Tumšā šokolāde", "Sauja riekstu vai dateles"],
];

// ---- 10 DIENAS ----
// meal.type: brokastis | otras | pusdienas | launags | vakarinas
// time = minūtes (gatavošana). a = alergēni.
export const days = [
  {
    n: 1, kcal: 1550, macros: { p: 93, t: 25, o: 220 },
    batch: "Vakarā izcep biezpiena plācenīšus — pusi atstāj 2. dienas brokastīm.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra", kcal: 350, time: 10, a: ["piens", "glutens", "rieksti"],
        ing: "60 g pilngraudu auzu pārslas, 100 ml vājpiens, 50 g ābols, 50 g apelsīns, 10 g zemesriekstu sviests.",
        steps: ["Auzu pārslas ar vājpienu vāra uz lēnas uguns 5–7 min, maisot.", "Ābolu un apelsīnu sagriež.", "Pārslas bļodā, virsū augļi un zemesriekstu sviests."] },
      { type: "otras", title: "Rupjmaize ar biezpienu", kcal: 280, time: 5, a: ["piens", "glutens"],
        ing: "70 g rupjmaize, 80 g biezpiens (0,5%), 20 g grieķu jogurts, 50 g gurķis, dilles, pētersīļi.",
        steps: ["Biezpienu sajauc ar jogurtu, dillēm un pētersīļiem.", "Uzziež uz maizes.", "Pasniedz ar svaigu gurķi."] },
      { type: "pusdienas", title: "Kuskuss ar dārzeņiem", kcal: 471, time: 20, a: ["glutens"],
        ing: "80 g kuskuss, 60 g vistas fileja, 20 g burkāni, 30 g paprika, 30 g spināti.",
        steps: ["Kuskusu aplej ar verdošu ūdeni un apsedz 5 min.", "Vistas fileju sagriež un apcep olīveļļā.", "Pievieno burkānu un papriku, sautē.", "Sajauc ar kuskusu un spinātiem."] },
      { type: "launags", title: "Augļi", kcal: 70, time: 2, a: [],
        ing: "50 g apelsīns, 50 g banāns.",
        steps: ["Augļus sagriež un apēd."] },
      { type: "vakarinas", title: "Biezpiena plācenīši", kcal: 378, time: 20, a: ["piens", "olas", "glutens"],
        ing: "180 g biezpiens (0,5%), 2 olas, 10 g medus, 80 g rīsu vai auzu milti, 10 g olīveļļa, šķipsniņa sāls. Pasniedz ar 50 g ogu un 15 g grieķu jogurta.",
        steps: ["Biezpienu, olas, medu, miltus un sāli samaisa.", "Pannu viegli iesmērē ar olīveļļu.", "Cep plācenīšus 2–3 min katrā pusē.", "Pusi atliek 2. dienas brokastīm. Pasniedz ar ogām un jogurtu."] },
    ],
  },
  {
    n: 2, kcal: 1403, macros: { p: 89, t: 57, o: 119 },
    batch: "Brokastīs ēd vakar pagatavotos biezpiena plācenīšus.",
    meals: [
      { type: "brokastis", title: "Biezpiena plācenīši (no 1. dienas)", kcal: 378, time: 3, a: ["piens", "olas", "glutens"],
        ing: "Vakar pagatavotie plācenīši ar 50 g svaigu ogu un 15 g grieķu jogurta.",
        steps: ["Plācenīšus uzsilda.", "Pasniedz ar ogām un jogurtu."] },
      { type: "otras", title: "Salāti ar vārītu olu", kcal: 326, time: 12, a: ["olas", "seklas"],
        ing: "50 g spināti, 50 g rukola, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 20 g saulespuķu sēklas, 10 g olīveļļa, 1 vārīta ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus saplūc un sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū pusē griezta ola."] },
      { type: "pusdienas", title: "Lēcas ar tvaicētiem dārzeņiem", kcal: 427, time: 30, a: [],
        ing: "100 g lēcas, 50 g ziedkāposts, 50 g cukīni, 30 g burkāns, 30 g paprika, 10 g olīveļļa, šķipsniņa sāls.",
        steps: ["Lēcas novāra (~20 min).", "Ziedkāpostu, cukīni, burkānu un papriku tvaicē 8–10 min.", "Sajauc, pārlej ar olīveļļu, sāli pievieno gatavam."] },
      { type: "launags", title: "Augļi", kcal: 50, time: 2, a: [],
        ing: "50 g apelsīns, 50 g ābols.",
        steps: ["Augļus sagriež un apēd."] },
      { type: "vakarinas", title: "Baltā zivs ar dārzeņiem", kcal: 223, time: 30, a: ["zivs"],
        ing: "100 g baltās zivs fileja (heks, menca), 50 g burkāni, 50 g paprika, 50 g cukīni, 50 g ziedkāposts, 10 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs, pipari.", "Cep 20–25 min, sāli pievieno gatavam."] },
    ],
  },
  {
    n: 3, kcal: 1467, macros: { p: 77, t: 69, o: 130 },
    batch: "Pusdienās gatavo pupiņu sautējumu (2 porcijas) un vakarā krēmzupu (2 porcijas) — pusi katram atstāj 4. dienai.",
    meals: [
      { type: "brokastis", title: "Omlete ar dārzeņiem", kcal: 317, time: 12, a: ["olas", "piens"],
        ing: "2 olas (180 g), 10 g olīveļļa, 30 g spināti, 30 g šampinjoni, 10 g sīpoli, 30 g liess siers (10%).",
        steps: ["Olas sakuļ.", "Olīveļļā uz pannas ielej olu masu.", "Virsū spinātus, šampinjonus, sīpolu un sieru.", "Cep zem vāka 4–5 min."] },
      { type: "otras", title: "Burkānu salāti ar maizi un kefīru", kcal: 526, time: 8, a: ["piens", "glutens", "seklas"],
        ing: "100 g rīvēti burkāni, 10 g olīveļļa, 20 g ķirbju sēklas, 70 g rupjmaize, 200 ml kefīrs.",
        steps: ["Burkānus sarīvē.", "Pievieno olīveļļu un ķirbju sēklas.", "Pasniedz ar maizes šķēli un glāzi kefīra."] },
      { type: "pusdienas", title: "Pupiņu sautējums", kcal: 222, time: 25, a: ["soja"],
        ing: "200 g vārītas pupiņas, 50 g spināti, 50 g tomāti, 50 g šampinjoni, 100 g tofu, 30 g sīpoli, pētersīļi, pipari, sāls. (2 porcijas — puse 4. dienai.)",
        steps: ["Sīpolu apcep olīveļļā.", "Pievieno šampinjonus, tomātus un spinātus.", "Pievieno pupiņas un tofu.", "Sautē 15 min, piedevā garšvielas. Pusi atliek 4. dienai."] },
      { type: "launags", title: "Rīsu galetes ar greipfrūtu", kcal: 216, time: 3, a: ["rieksti"],
        ing: "2 pilngraudu rīsu galetes, 20 g zemesriekstu sviests, 1 greipfrūts.",
        steps: ["Galetes apziež ar zemesriekstu sviestu.", "Pasniedz ar greipfrūtu."] },
      { type: "vakarinas", title: "Ķirbja krēmzupa", kcal: 186, time: 30, a: ["piens"],
        ing: "100 g ķirbis, 30 g sīpoli, 10 g ķiploki, 40 g burkāni, 50 g kartupeļi, 30 g kausētais siers, 150 ml ūdens, paprika, pipari, sāls, 20 g ķirbju sēklas. (2 porcijas — puse 4. dienai.)",
        steps: ["Sīpolu un ķiploku apcep.", "Pievieno ķirbi, burkānu, kartupeli un ūdeni.", "Vāra ~20 min, līdz mīksts.", "Pievieno kausēto sieru, sablenderē.", "Dekorē ar ķirbju sēklām. Pusi atliek 4. dienai."] },
    ],
  },
  {
    n: 4, kcal: 1360, macros: { p: 90, t: 41, o: 158 },
    batch: "Ēd vakar gatavoto pupiņu sautējumu un krēmzupu.",
    meals: [
      { type: "brokastis", title: "Griķu pārslu putra", kcal: 371, time: 8, a: ["piens", "rieksti"],
        ing: "60 g griķu pārslas, 100 ml vājpiens (var aplaistīt vai vārīt ūdenī), 80 g vājpiena biezpiens, 10 g zemesriekstu sviests.",
        steps: ["Griķu pārslas aplej ar karstu vājpienu vai īsi pavāra.", "Pievieno biezpienu un zemesriekstu sviestu."] },
      { type: "otras", title: "Pupiņu sautējums (no 3. dienas) ar kefīru", kcal: 322, time: 3, a: ["soja", "piens"],
        ing: "Vakar gatavotais pupiņu sautējums un 1 glāze kefīra.",
        steps: ["Sautējumu uzsilda.", "Pasniedz ar glāzi kefīra."] },
      { type: "pusdienas", title: "Ķirbja krēmzupa (no 3. dienas)", kcal: 186, time: 3, a: ["piens"],
        ing: "Vakar gatavotā krēmzupa.",
        steps: ["Zupu uzsilda un pasniedz."] },
      { type: "launags", title: "Augļu salāti", kcal: 253, time: 5, a: ["piens"],
        ing: "50 g kivi, 50 g apelsīns, 50 g ābols, 10 g medus, 50 g grieķu jogurts.",
        steps: ["Augļus sagriež.", "Sajauc ar jogurtu un medu."] },
      { type: "vakarinas", title: "Forele ar dārzeņiem", kcal: 228, time: 30, a: ["zivs"],
        ing: "100 g foreles fileja, 50 g baklažāns, 50 g ziedkāposts, 50 g paprika, 50 g saldais kartupelis.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas.", "Virsū forele, sāls, pipari.", "Cep ~20 min."] },
    ],
  },
  {
    n: 5, kcal: 1383, macros: { p: 64, t: 47, o: 181 },
    batch: "Čia pudiņu vislabāk samaisīt jau iepriekšējā vakarā.",
    meals: [
      { type: "brokastis", title: "Čia pudiņš ar ogām", kcal: 354, time: 5, a: ["piens", "seklas"],
        ing: "50 g čia sēklas, 100 ml vājpiens (0,5%), 10 g medus, 100 g svaigas ogas.",
        steps: ["Čia sēklas, vājpienu un medu samaisa.", "Ledusskapī vismaz 20 min (labāk visu nakti).", "Virsū svaigas ogas."] },
      { type: "otras", title: "Banāns ar tumšo šokolādi", kcal: 202, time: 1, a: [],
        ing: "1 banāns, 3 gabaliņi tumšās šokolādes (vismaz 70%).",
        steps: ["Apēd banānu ar šokolādi."] },
      { type: "pusdienas", title: "Grūbas ar dārzeņiem", kcal: 405, time: 40, a: ["glutens"],
        ing: "80 g grūbas, 30 g burkāni, 30 g paprika, 30 g šampinjoni, 30 g cukīni, 20 g sīpoli, 5 g ķiploki, dilles, pētersīļi, 10 g olīveļļa, pipari, sāls.",
        steps: ["Grūbas novāra (~30–40 min).", "Dārzeņus apcep olīveļļā.", "Sajauc grūbas ar dārzeņiem un garšvielām."] },
      { type: "launags", title: "Augļu salāti", kcal: 156, time: 5, a: ["piens"],
        ing: "50 g banāns, 50 g kivi, 50 g persiks, 10 g medus, 50 g grieķu jogurts.",
        steps: ["Augļus sagriež.", "Sajauc ar jogurtu un medu."] },
      { type: "vakarinas", title: "Salāti ar tītara fileju", kcal: 265, time: 25, a: [],
        ing: "60 g kalē kāposts, 30 g paprika, 30 g tomāti, 30 g gurķi, 100 g cepta tītara fileja, 10 g olīveļļa, baziliks, pipari, sāls.",
        steps: ["Tītara fileju cep krāsnī vai uz pannas.", "Kāli, papriku, tomātu un gurķi sagriež.", "Sajauc, pārlej ar olīveļļu, virsū tītars."] },
    ],
  },
  {
    n: 6, kcal: 1599, macros: { p: 90, t: 64, o: 154 },
    batch: "Šodien jaunas receptes — nekas no iepriekšējās dienas.",
    meals: [
      { type: "brokastis", title: "Smūtija bļoda", kcal: 480, time: 8, a: ["piens", "rieksti", "glutens"],
        ing: "1 banāns, 30 g saldētas ogas, 40 ml vājpiens, 40 g spināti. Virsū 6 rieksti, 100 g ogu, 40 g grauzdētu auzu pārslu.",
        steps: ["Banānu, ogas, vājpienu un spinātus sablenderē.", "Ielej bļodā.", "Virsū rieksti, svaigas ogas un grauzdētas auzu pārslas."] },
      { type: "otras", title: "Pilngraudu tortiljas pica", kcal: 302, time: 12, a: ["glutens", "piens"],
        ing: "1 pilngraudu tortilja, 10 g pesto, 20 g spināti, 30 g ķiršu tomāti, 20 g sīpoli, 20 g šampinjoni, 30 g liess siers (10%).",
        steps: ["Tortilju apziež ar pesto.", "Virsū spinātus, tomātus, sīpolu, šampinjonus un sieru.", "Cep 200°C 8–10 min."] },
      { type: "pusdienas", title: "Salāti ar vistas fileju", kcal: 359, time: 25, a: [],
        ing: "60 g kalē kāposts, 30 g paprika, 30 g tomāti, 30 g gurķi, 100 g cepta vistas fileja, 10 g olīveļļa, baziliks, pipari, sāls.",
        steps: ["Vistas fileju cep krāsnī vai uz pannas.", "Dārzeņus sagriež.", "Sajauc, pārlej ar olīveļļu, virsū vista."] },
      { type: "launags", title: "Rīsu galetes ar persiku", kcal: 233, time: 3, a: ["rieksti"],
        ing: "2 rīsu galetes, 20 g zemesriekstu sviests, 1 persiks.",
        steps: ["Galetes apziež ar zemesriekstu sviestu.", "Pasniedz ar persiku."] },
      { type: "vakarinas", title: "Baltā zivs ar dārzeņiem", kcal: 224, time: 30, a: ["zivs"],
        ing: "100 g baltās zivs fileja, 50 g baklažāns, 50 g paprika, 50 g cukīni, 50 g Briseles kāposti, 10 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs un pipari.", "Cep 20–25 min."] },
    ],
  },
  {
    n: 7, kcal: 1376, macros: { p: 63, t: 51, o: 148 },
    batch: "Vakariņās gatavo 2 pildītas paprikas — vienu atstāj 8. dienas launagam.",
    meals: [
      { type: "brokastis", title: "Muslis ar ogām", kcal: 350, time: 3, a: ["piens", "glutens", "rieksti"],
        ing: "50 g muslis (mazāk pievienota cukura), 50 g banāns, 70 g grieķu jogurts, 100 g svaigas ogas.",
        steps: ["Musli liek bļodā.", "Virsū jogurts, sagriezts banāns un ogas."] },
      { type: "otras", title: "Salāti ar vārītu olu", kcal: 328, time: 12, a: ["olas", "seklas"],
        ing: "50 g romiešu salāts, 50 g spināti, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 20 g saulespuķu sēklas, 10 g olīveļļa, 1 vārīta ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū ola."] },
      { type: "pusdienas", title: "Lēcas ar sautētiem dārzeņiem", kcal: 433, time: 30, a: [],
        ing: "100 g lēcas, 30 g brokolis, 40 g burkāni, 40 g kālis (kolrābis), 30 g šampinjoni, 10 g olīveļļa.",
        steps: ["Lēcas novāra (~20 min).", "Dārzeņus sautē olīveļļā 8–10 min.", "Sajauc kopā."] },
      { type: "launags", title: "Apelsīns", kcal: 47, time: 1, a: [],
        ing: "1 apelsīns.",
        steps: ["Apēd apelsīnu."] },
      { type: "vakarinas", title: "Pildīta paprika", kcal: 219, time: 40, a: ["piens"],
        ing: "2 paprikas, 150 g vārīti brūnie rīsi, 20 g sīpoli, 40 g burkāni, 40 g cukīni, 40 g tomāti, 5 g ķiploki, pētersīļi, dilles, 10 g olīveļļa, pipari, paprika, sāls, 20 g krējums (10–15%). (2 gab — viena 8. dienai.)",
        steps: ["Rīsus novāra.", "Dārzeņus sagriež un apcep olīveļļā.", "Sajauc ar rīsiem un garšvielām.", "Papriku pilda un cep 200°C 25–30 min. Virsū krējums. Vienu atstāj 8. dienai."] },
    ],
  },
  {
    n: 8, kcal: 1596, macros: { p: 106, t: 46, o: 162 },
    batch: "Launagā ēd vakar gatavoto pildīto papriku.",
    meals: [
      { type: "brokastis", title: "Griķu pārslu putra ar biezpienu", kcal: 297, time: 8, a: ["piens"],
        ing: "60 g griķu pārslas, 100 ml vājpiens, 60 g vājpiena biezpiens, zaļumi, 20 g ķiršu tomāti.",
        steps: ["Griķu pārslas aplej ar karstu vājpienu.", "Pasniedz ar biezpienu, zaļumiem un tomātiem."] },
      { type: "otras", title: "Tortilja ar pupiņām", kcal: 377, time: 10, a: ["glutens", "piens", "soja"],
        ing: "1 pilngraudu tortilja, 100 g vārītas pupiņas, 20 g šampinjoni, sauja spinātu, 30 g liess siers (10%).",
        steps: ["Tortilju pilda ar pupiņām, šampinjoniem un spinātiem.", "Pārkaisa ar sieru.", "Saloka un uzsilda uz pannas."] },
      { type: "pusdienas", title: "Vista ar dārzeņiem", kcal: 406, time: 30, a: [],
        ing: "100 g vistas fileja, 50 g saldais kartupelis, 50 g kālis (kolrābis), 30 g paprika, 30 g burkāni, 10 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Vistu un dārzeņus liek uz pannas, pārlej olīveļļu.", "Cep ~25 min."] },
      { type: "launags", title: "Pildīta paprika (no 7. dienas)", kcal: 219, time: 3, a: ["piens"],
        ing: "Vakar gatavotā pildītā paprika.",
        steps: ["Papriku uzsilda un apēd."] },
      { type: "vakarinas", title: "Salāti ar garnelēm", kcal: 298, time: 12, a: ["juras"],
        ing: "60 g rukola, 30 g tomāti, 30 g gurķi, 50 g avokado, 30 g paprika, 100 g garneles, baziliks, 10 g olīveļļa.",
        steps: ["Garneles apcep olīveļļā 3–4 min.", "Dārzeņus un avokado sagriež.", "Sajauc, virsū garneles un baziliks."] },
    ],
  },
  {
    n: 9, kcal: 1325, macros: { p: 75, t: 53, o: 210 },
    batch: "Pusdienās gatavo laša zupu (2 porcijas) un vakarā vistas sautējumu — pusi katram atstāj 10. dienai.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra ar ievārījumu", kcal: 328, time: 10, a: ["piens", "glutens", "rieksti"],
        ing: "60 g pilngraudu auzu pārslas, 100 ml vājpiens (0,5%), 10 g ievārījums, 10 g zemesriekstu sviests.",
        steps: ["Auzu pārslas ar vājpienu pavāra 5–7 min.", "Virsū ievārījums un zemesriekstu sviests."] },
      { type: "otras", title: "Salāti ar vārītu olu", kcal: 328, time: 12, a: ["olas", "seklas"],
        ing: "50 g romiešu salāts, 50 g spināti, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 20 g saulespuķu sēklas, 10 g olīveļļa, 1 vārīta ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū ola."] },
      { type: "pusdienas", title: "Laša zupa", kcal: 240, time: 30, a: ["zivs"],
        ing: "150 g laša fileja, 100 g kartupeļi, 50 g burkāni, 30 g sīpoli, 20 g zivju mērce, 50 g šampinjoni, 20 g selerija, zaļumi, 1 l ūdens. (2 porcijas — puse 10. dienai.)",
        steps: ["Kartupeli, burkānu, sīpolu un seleriju vāra ūdenī.", "Pievieno šampinjonus un sagrieztu lasi.", "Pievieno zivju mērci un zaļumus.", "Vāra ~10 min. Pusi atliek 10. dienai."] },
      { type: "launags", title: "Augļu salāti", kcal: 145, time: 5, a: ["piens"],
        ing: "50 g kivi, 50 g mango, 50 g apelsīns, 10 g medus, 50 g grieķu jogurts.",
        steps: ["Augļus sagriež.", "Sajauc ar jogurtu un medu."] },
      { type: "vakarinas", title: "Vistas gaļas sautējums", kcal: 285, time: 35, a: [],
        ing: "150 g liesa vistas gaļa, 100 g kartupeļi, 50 g cukīni, 50 g ziedkāposts, 50 g burkāni, 10 g olīveļļa, 10 g sīpoli, 5 g ķiploki, sāls, pipari. (puse 10. dienai.)",
        steps: ["Vistu apcep olīveļļā.", "Pievieno sīpolu, ķiploku un dārzeņus.", "Sautē ~20 min. Pusi atliek 10. dienai."] },
    ],
  },
  {
    n: 10, kcal: 1439, macros: { p: 101, t: 44, o: 126 },
    batch: "Ēd vakar gatavoto vistas sautējumu un laša zupu.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar biezpienu un avokado", kcal: 362, time: 7, a: ["piens", "glutens"],
        ing: "70 g rupjmaize, 60 g biezpiens (0,5%), 60 g grieķu jogurts, dilles, pētersīļi, 50 g avokado.",
        steps: ["Biezpienu sajauc ar jogurtu un zaļumiem.", "Uzziež uz maizes.", "Virsū sagriezts avokado."] },
      { type: "otras", title: "Vistas sautējums (no 9. dienas)", kcal: 285, time: 3, a: [],
        ing: "Vakar gatavotais vistas gaļas sautējums (200 g).",
        steps: ["Sautējumu uzsilda un apēd."] },
      { type: "pusdienas", title: "Laša zupa (no 9. dienas) ar maizi", kcal: 432, time: 5, a: ["zivs", "glutens"],
        ing: "Vakar gatavotā laša zupa (200 g) ar 70 g rupjmaizes.",
        steps: ["Zupu uzsilda.", "Pasniedz ar maizes šķēli."] },
      { type: "launags", title: "Biešu salāti ar olu", kcal: 144, time: 3, a: ["olas", "piens"],
        ing: "100 g vārītas rīvētas bietes, 10 g krējums (12%), 1 vārīta ola.",
        steps: ["Bietes sarīvē un sajauc ar krējumu.", "Pasniedz ar pusē grieztu olu."] },
      { type: "vakarinas", title: "Salāti ar garnelēm", kcal: 216, time: 12, a: ["juras"],
        ing: "60 g spināti, 30 g tomāti, 30 g gurķi, 30 g paprika, 100 g garneles, baziliks, 10 g olīveļļa.",
        steps: ["Garneles apcep olīveļļā 3–4 min.", "Dārzeņus sagriež.", "Sajauc, virsū garneles un baziliks."] },
    ],
  },
];

// ---- IEPIRKUMU DATI pa dienām (produkts -> grami; vai [skaits,'gab']) ----
// Skripts tos saskaita kopā nedēļas sarakstā.
export const shoppingByDay = {
  1: { "Pilngraudu auzu pārslas": 60, "Vājpiens": 100, "Ābols": 50, "Apelsīns": 100, "Zemesriekstu sviests": 10, "Rupjmaize": 70, "Biezpiens": 260, "Grieķu jogurts": 35, "Gurķi": 50, "Dilles": 10, "Pētersīļi": 10, "Kuskuss": 80, "Vistas fileja": 60, "Burkāni": 20, "Paprika": 30, "Spināti": 30, "Banāns": 50, "Olas": [2, "gab"], "Medus": 10, "Rīsu milti": 80, "Olīveļļa": 10, "Svaigas ogas": 50 },
  2: { "Svaigas ogas": 50, "Grieķu jogurts": 15, "Spināti": 50, "Rukola": 50, "Gurķi": 30, "Tomāti": 30, "Sēklu dīgsti": 20, "Paprika": 110, "Saulespuķu sēklas": 20, "Olīveļļa": 30, "Olas": [1, "gab"], "Lēcas": 100, "Ziedkāposts": 100, "Cukīni": 100, "Burkāni": 80, "Apelsīns": 50, "Ābols": 50, "Baltā zivs": 100 },
  3: { "Olas": [2, "gab"], "Olīveļļa": 20, "Spināti": 80, "Šampinjoni": 80, "Sīpoli": 70, "Liess siers": 30, "Ķirbju sēklas": 40, "Burkāni": 140, "Rupjmaize": 70, "Kefīrs": 200, "Vārītas pupiņas": 200, "Tomāti": 50, "Tofu": 100, "Pētersīļi": 10, "Rīsu galetes": [2, "gab"], "Zemesriekstu sviests": 20, "Greipfrūts": 100, "Ķirbis": 100, "Ķiploki": 10, "Kartupeļi": 50, "Kausētais siers": 30 },
  4: { "Griķu pārslas": 60, "Vājpiens": 100, "Biezpiens": 80, "Zemesriekstu sviests": 10, "Ķirbju sēklas": 20, "Kefīrs": 200, "Kivi": 50, "Apelsīns": 50, "Ābols": 50, "Medus": 10, "Grieķu jogurts": 50, "Tumšā šokolāde": 20, "Forele": 100, "Baklažāns": 50, "Ziedkāposts": 50, "Paprika": 50, "Saldais kartupelis": 50 },
  5: { "Čia sēklas": 50, "Vājpiens": 100, "Medus": 20, "Svaigas ogas": 100, "Banāns": 150, "Tumšā šokolāde": 20, "Grūbas": 80, "Burkāni": 30, "Paprika": 60, "Šampinjoni": 30, "Cukīni": 30, "Sīpoli": 20, "Ķiploki": 5, "Dilles": 10, "Pētersīļi": 10, "Olīveļļa": 20, "Kivi": 50, "Persiki": 50, "Grieķu jogurts": 50, "Kalē kāposts": 60, "Tomāti": 30, "Gurķi": 30, "Tītara fileja": 100, "Baziliks": 10 },
  6: { "Banāns": 100, "Svaigas ogas": 130, "Vājpiens": 40, "Spināti": 60, "Rieksti (mandeles, valrieksti)": 30, "Pilngraudu auzu pārslas": 40, "Pilngraudu tortilja": [1, "gab"], "Pesto": 10, "Tomāti": 60, "Sīpoli": 20, "Šampinjoni": 20, "Liess siers": 30, "Kalē kāposts": 60, "Paprika": 80, "Gurķi": 30, "Vistas fileja": 100, "Olīveļļa": 20, "Baziliks": 5, "Rīsu galetes": [2, "gab"], "Zemesriekstu sviests": 20, "Persiki": 150, "Baltā zivs": 100, "Baklažāns": 50, "Cukīni": 50, "Briseles kāposti": 50 },
  7: { "Muslis": 50, "Banāns": 50, "Grieķu jogurts": 70, "Svaigas ogas": 100, "Romiešu salāti": 50, "Spināti": 50, "Gurķi": 30, "Tomāti": 70, "Sēklu dīgsti": 20, "Paprika": 260, "Saulespuķu sēklas": 20, "Olīveļļa": 30, "Olas": [1, "gab"], "Lēcas": 100, "Brokolis": 30, "Burkāni": 80, "Kālis (kolrābis)": 40, "Šampinjoni": 30, "Apelsīns": 100, "Brūnie rīsi": 150, "Sīpoli": 20, "Cukīni": 40, "Ķiploki": 5, "Krējums": 20 },
  8: { "Griķu pārslas": 60, "Vājpiens": 100, "Biezpiens": 60, "Tomāti": 50, "Pilngraudu tortilja": [1, "gab"], "Vārītas pupiņas": 100, "Šampinjoni": 20, "Spināti": 20, "Liess siers": 30, "Vistas fileja": 100, "Saldais kartupelis": 50, "Kālis (kolrābis)": 50, "Paprika": 60, "Burkāni": 70, "Olīveļļa": 20, "Krējums": 20, "Rukola": 60, "Gurķi": 30, "Avokado": 50, "Garneles": 100, "Baziliks": 5 },
  9: { "Pilngraudu auzu pārslas": 60, "Vājpiens": 100, "Ievārījums": 10, "Zemesriekstu sviests": 10, "Romiešu salāti": 50, "Spināti": 50, "Gurķi": 30, "Tomāti": 30, "Sēklu dīgsti": 20, "Paprika": 30, "Saulespuķu sēklas": 20, "Olīveļļa": 20, "Olas": [1, "gab"], "Lasis": 150, "Kartupeļi": 200, "Burkāni": 100, "Sīpoli": 40, "Zivju mērce": 20, "Šampinjoni": 50, "Zaļumi": 20, "Kivi": 50, "Mango": 50, "Apelsīns": 50, "Medus": 10, "Grieķu jogurts": 50, "Vistas fileja": 150, "Cukīni": 50, "Ziedkāposts": 50, "Ķiploki": 5 },
  10: { "Rupjmaize": 140, "Biezpiens": 60, "Grieķu jogurts": 60, "Dilles": 5, "Pētersīļi": 5, "Avokado": 50, "Olīveļļa": 10, "Bietes": 100, "Krējums": 10, "Olas": [1, "gab"], "Spināti": 60, "Tomāti": 30, "Gurķi": 30, "Paprika": 30, "Garneles": 100, "Baziliks": 5 },
};

// Produktu katalogs: kategorija + iepakojuma ieteikums
export const catalog = {
  "Pilngraudu auzu pārslas": ["Graudi un putraimi", "1 paka (500 g)"],
  "Griķu pārslas": ["Graudi un putraimi", "1 paka (400–500 g)"],
  "Kuskuss": ["Graudi un putraimi", "1 paka"],
  "Grūbas": ["Graudi un putraimi", "1 paka"],
  "Brūnie rīsi": ["Graudi un putraimi", "1 paka"],
  "Muslis": ["Graudi un putraimi", "1 maza paka"],
  "Lēcas": ["Graudi un putraimi", "1 paka"],
  "Vārītas pupiņas": ["Graudi un putraimi", "2 bundžas vai 1 paka sausu"],
  "Čia sēklas": ["Graudi un putraimi", "1 maza paka"],
  "Rīsu milti": ["Graudi un putraimi", "1 maza paka"],
  "Rupjmaize": ["Maize", "1 klaips (bez rauga)"],
  "Rīsu galetes": ["Maize", "1 paka"],
  "Pilngraudu tortilja": ["Maize", "1 paka"],
  "Vājpiens": ["Piena produkti", "1 l"],
  "Biezpiens": ["Piena produkti", "1 paka (0,5%)"],
  "Grieķu jogurts": ["Piena produkti", "1 paka"],
  "Kefīrs": ["Piena produkti", "0,5 l"],
  "Liess siers": ["Piena produkti", "1 gabals (10%)"],
  "Kausētais siers": ["Piena produkti", "1 maza paka"],
  "Krējums": ["Piena produkti", "1 maza paka (10–15%)"],
  "Olas": ["Olas", "10 gab kaste"],
  "Tofu": ["Olbaltums", "1 paka"],
  "Vistas fileja": ["Gaļa un zivs", "~450 g"],
  "Tītara fileja": ["Gaļa un zivs", "~100 g"],
  "Baltā zivs": ["Gaļa un zivs", "~200 g (heks/menca)"],
  "Forele": ["Gaļa un zivs", "~100 g"],
  "Lasis": ["Gaļa un zivs", "~150 g"],
  "Garneles": ["Gaļa un zivs", "~200 g"],
  "Spināti": ["Dārzeņi un zaļumi", "1 paka"],
  "Rukola": ["Dārzeņi un zaļumi", "1 paka"],
  "Romiešu salāti": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Kalē kāposts": ["Dārzeņi un zaļumi", "1 sauja"],
  "Gurķi": ["Dārzeņi un zaļumi", "1–2 gab"],
  "Tomāti": ["Dārzeņi un zaļumi", "~400 g"],
  "Paprika": ["Dārzeņi un zaļumi", "~5–6 gab"],
  "Burkāni": ["Dārzeņi un zaļumi", "~600 g"],
  "Cukīni": ["Dārzeņi un zaļumi", "1–2 gab"],
  "Ziedkāposts": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Brokolis": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Briseles kāposti": ["Dārzeņi un zaļumi", "1 maza paka"],
  "Baklažāns": ["Dārzeņi un zaļumi", "1 gab"],
  "Šampinjoni": ["Dārzeņi un zaļumi", "1 paka"],
  "Sīpoli": ["Dārzeņi un zaļumi", "~3 gab"],
  "Ķiploki": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Ķirbis": ["Dārzeņi un zaļumi", "1 gabals"],
  "Kartupeļi": ["Dārzeņi un zaļumi", "~350 g"],
  "Saldais kartupelis": ["Dārzeņi un zaļumi", "1 gab"],
  "Kālis (kolrābis)": ["Dārzeņi un zaļumi", "1 gab"],
  "Bietes": ["Dārzeņi un zaļumi", "1 vārīta biete"],
  "Sēklu dīgsti": ["Dārzeņi un zaļumi", "1 maza paka"],
  "Zaļumi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Dilles": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Pētersīļi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Baziliks": ["Dārzeņi un zaļumi", "1 podiņš"],
  "Ābols": ["Augļi", "~3 gab"],
  "Apelsīns": ["Augļi", "~4 gab"],
  "Banāns": ["Augļi", "~5 gab"],
  "Kivi": ["Augļi", "~3 gab"],
  "Persiki": ["Augļi", "~2 gab"],
  "Mango": ["Augļi", "1 gab"],
  "Greipfrūts": ["Augļi", "1 gab"],
  "Svaigas ogas": ["Augļi", "~500 g (var saldētas)"],
  "Zemesriekstu sviests": ["Rieksti un sēklas", "1 burka"],
  "Rieksti (mandeles, valrieksti)": ["Rieksti un sēklas", "1 maza paka"],
  "Saulespuķu sēklas": ["Rieksti un sēklas", "1 maza paka"],
  "Ķirbju sēklas": ["Rieksti un sēklas", "1 maza paka"],
  "Olīveļļa": ["Eļļas, garšvielas, citi", "Extra Virgin, 1 pudele"],
  "Medus": ["Eļļas, garšvielas, citi", "1 burka"],
  "Pesto": ["Eļļas, garšvielas, citi", "1 maza burka"],
  "Ievārījums": ["Eļļas, garšvielas, citi", "1 burka"],
  "Zivju mērce": ["Eļļas, garšvielas, citi", "1 pudelīte"],
  "Tumšā šokolāde": ["Eļļas, garšvielas, citi", "1 tāfelīte (≥70%)"],
};


