// Saturs — Ievas Jēkabsones 10 dienu ēdienreižu plāns
// Visi teksti latviešu valodā, UTF-8. Skaitļi rēķinās no receptēm, sk. kopigais/uzturvertibas.mjs.
import {
  philosophy, aboutLead, disclaimer, tips, adapt, howToUseSteps, swapsBase,
} from "../kopigais/kopigie-teksti.mjs";

export { allergens, sections, sectionOrder } from "../kopigais/kopigie-teksti.mjs";

export const meta = {
  title: "Veselīgu recepšu un ēdienreižu plāns",
  subtitle: "10 dienām",
  author: "Ieva Jēkabsone",
  authorRole: "uztura konsultante",
  site: "ievajekabsone.lv",
};

// Kas šajā produktā atšķiras no pārējiem diviem. Dzinējs (`kopigais/build.mjs`) ir viens.
export const product = {
  pdfName: "10-Dienu-Uztura-Plans",
  cover: "vinka-fit-10-dienu-uztura-plans-vaks-luxury-02.webp",
  coverKicker: "Uztura ceļvedis",
  coverTitle: "Veselīgu recepšu un<br>ēdienreižu plāns",
  coverTag: "Sabalansētas, ātri pagatavojamas receptes ar izrēķinātām kalorijām, iepirkumu sarakstu un pagatavošanas soļiem.",
  mealprepLead: "Sešas receptes plānā gatavo lielāku porciju. Daļu apēd uzreiz, otru — nākamajā dienā. Tā tu pavadi mazāk laika virtuvē.",
  aboutPhoto: ["ieva-sabalansets-pusdienu-skivis-lasis-kvinoja.webp", "Sabalansēts pusdienu šķīvis ar lasi un kvinoju — Ieva Jēkabsone, uztura konsultante"],
  prepPairs: [
    ["1. diena · vakariņas", "Biezpiena plācenīši", "2. diena · brokastis"],
    ["3. diena · pusdienas", "Pupiņu sautējums ar tofu", "4. diena · otrās brokastis"],
    ["3. diena · vakariņas", "Ķirbja krēmzupa ar lēcām", "4. diena · pusdienas"],
    ["7. diena · vakariņas", "Pildīta paprika ar vistu", "8. diena · launags"],
    ["9. diena · pusdienas", "Laša zupa", "10. diena · pusdienas"],
    ["9. diena · vakariņas", "Vistas gaļas sautējums", "10. diena · otrās brokastis"],
  ],
};

export const copy = {
  howToUseLead:
    "Šis plāns ir desmit dienu sākums, ne mūža diēta. Katrai dienai ir piecas ēdienreizes, izrēķinātas kalorijas un iepirkumu saraksts. Ej secīgi vai izvēlies dienas, kas patīk.",
  howToUseSteps,
  aboutLead,
  philosophy,
  forWhom:
    "Šis ir līdzsvarots plāns ar aptuveni 1400–1560 kcal dienā. Tas ir maigs sākums, ne ekstrēma diēta. Kalorijas aprēķinātas vidējām vajadzībām, neņemot vērā fizisko slodzi. Ja esi fiziski aktīvs, vīrietis vai vienkārši jūties izsalcis — pievieno porciju vai uzkodu. Klausies savu ķermeni.",
  adapt,
  disclaimer,
  // Olu ieteikums ir tikai tur, kur plānā olas tiešām ir.
  tips: [...tips.slice(0, 7), "Olas izvēlies no brīvībā augušām vistām un eko saimniecības, ja iespējams.", tips[7]],
  faq: [
    ["Vai šis ir svara zaudēšanas plāns?", "Tas ir līdzsvarots reset. Daudziem aptuveni 1510 kcal nozīmē vieglu deficītu, bet rezultāts atkarīgs no tavām vajadzībām un aktivitātes."],
    ["Vai drīkstu mainīt receptes?", "Jā. Tas ir mērķis. Pielāgo plānu savai garšai un produktiem, kas pieejami."],
    ["Cik daudz ūdens jādzer?", "Vismaz 2 l dienā. No tā vismaz 1,5 l lai ir tīrs ūdens."],
    ["Vai produkti jāsver?", "Sākumā jā. Dārzeņus un putru ar laiku vari likt no acs, bet riekstus, sēklas, eļļu un sierus sver arī pēc tam — tajos ir visvairāk kaloriju uz gramu."],
    ["Ko darīt ar sāli un cukuru?", "Sāli pievieno gatavam ēdienam un maz. Dzērieniem cukuru nepievieno."],
    ["Kas notiek pēc 10 dienām?", "Turpini tos pašus principus: dārzeņi, olbaltums, pilngraudi un ūdens. Atkārto plānu vai veido savu."],
  ],
};

// Aizstāšanas tabula
// Aizstāšanas saraksts — Ievas "pielāgošana, ne aizliegumi" princips produktā.
// Struktūra: [kategorija, [[no, uz, kas jāievēro], ...]]
// Trešā kolonna ir svarīgākā: tā māca, KĀPĒC maiņa strādā, ne tikai KO likt vietā.
export const swaps = [
  ["Gaļa, zivs, olas", [
    ["Vistas fileja", "Tītara fileja, liesa cūkgaļas karbonāde", "Gatavošanas laiks līdzīgs. Tītars ir sausāks — necep pārāk ilgi."],
    ["Baltā zivs (menca, heks)", "Forele, lasis vai vista", "Lasis ir taukaināks. Ja liec to vietā, porciju ņem mazliet mazāku."],
    ["Lasis", "Forele vai skumbrija", "Abas ir treknās zivis ar to pašu lomu maltītē."],
    ["Garneles", "Vista, tofu vai baltā zivs", "Garneles gatavojas 3 minūtēs, vista — apmēram 10. Rēķinies ar laiku."],
    ["Olas", "Tofu (kultenī), biezpiens", "Olu vietā tofu ņem apmēram pusotru reizi vairāk pēc svara."],
    ["Tofu", "Vārītas pupiņas, lēcas vai vista", "Tofu pats par sevi ir bez garšas — garšvielas un mērce nav neobligātas."],
  ]],
  ["Piena produkti", [
    ["Vājpiens", "Auzu vai mandeļu dzēriens", "Izvēlies bez pievienota cukura — saldinātajā ir līdz 7 g cukura uz 100 ml."],
    ["Biezpiens", "Grieķu jogurts vai skyr", "Ņem nesaldinātu. Saldinātajā mēdz būt divreiz vairāk cukura."],
    ["Grieķu jogurts", "Biezpiens ar karoti kefīra", "Konsistence sanāks biezāka — kefīru pievieno pamazām."],
    ["Kefīrs", "Naturāls jogurts vai paniņas", "Der arī augu jogurts, ja piens nepatīk vai nepanes."],
    ["Liess siers", "Fetas siers vai mocarella", "Feta ir daudz sāļāka — tad ēdienam sāli vairs nepievieno."],
    ["Krējums", "Grieķu jogurts vai krējums 10%", "Jogurtu pievieno jau gatavam ēdienam, ne verdošam — citādi tas sarecēs."],
  ]],
  ...swapsBase,
];

// Ja no visas produktu grupas jāatsakās — īss ceļvedis.
export const dietSwaps = [
  ["Bez laktozes", "Piena produktus maini pret bezlaktozes vai augu versijām. Cietajos sieros laktozes tikpat kā nav."],
  ["Bez glutēna", "Kuskusu, grūbas un rupjmaizi maini pret rīsiem, griķiem vai kvinoju."],
  ["Veģetārietim", "Gaļu un zivi maini pret tofu, pupiņām, lēcām un olām. Olbaltumvielu daudzumu paturi to pašu."],
];

// ---- 10 DIENAS ----
// meal.type: brokastis | otras | pusdienas | launags | vakarinas
// time = minūtes (gatavošana). a = alergēni.
export const days = [
  {
    n: 1,
    batch: "Vakarā izcep biezpiena plācenīšus — pusi atstāj 2. dienas brokastīm.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra ar olu baltumiem", time: 12, a: ["piens", "glutens", "olas", "rieksti"],
        ing: "50 g pilngraudu auzu pārslas, 100 ml vājpiens (0,5 %), 2 olu baltumi, ½ ābols, 10 g zemesriekstu sviests.",
        steps: ["Auzu pārslas ar vājpienu vāra uz lēnas uguns 5–7 min, maisot.", "Olu baltumus sakuļ ar dakšiņu un ievieš putrā pēdējā minūtē, ātri maisot — tie sasaistās un putra kļūst krēmīgāka.", "Dzeltenumus neizmet: tos noglabā ledusskapī zem plēves un divu dienu laikā izmanto omletei vai mērcei.", "Ābolu sagriež.", "Pārslas bļodā, virsū ābols un zemesriekstu sviests."] },
      { type: "otras", title: "Rupjmaize ar biezpienu", time: 5, a: ["piens", "glutens"],
        ing: "70 g rupjmaize, 80 g biezpiens (0,5 %), 20 g grieķu jogurts (0 %), 50 g gurķi, dilles, pētersīļi.",
        steps: ["Biezpienu sajauc ar jogurtu, dillēm un pētersīļiem, uzziež uz maizes, pasniedz ar svaigu gurķi."] },
      { type: "pusdienas", title: "Kuskuss ar vistu un dārzeņiem", time: 20, a: ["glutens"],
        ing: "70 g kuskuss, 80 g vistas fileja, 20 g burkāni, 30 g paprika, 30 g spināti, 5 g olīveļļa.",
        steps: ["Kuskusu aplej ar verdošu ūdeni un apsedz 5 min.", "Vistas fileju sagriež un apcep olīveļļā.", "Pievieno burkānu un papriku, sautē.", "Sajauc ar kuskusu un spinātiem."] },
      { type: "launags", title: "Augļi ar biezpienu", time: 3, a: ["piens"],
        ing: "1 apelsīns, 60 g biezpiens (0,5 %).",
        steps: ["Augļus sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Biezpiena plācenīši", time: 20, portions: 2, a: ["piens", "olas", "glutens"],
        ing: "180 g biezpiens (0,5 %), 2 olas, 10 g medus, 60 g rīsu vai auzu milti, 7 g olīveļļa, šķipsniņa sāls.",
        serve: "50 g svaigas ogas, 15 g grieķu jogurts (0 %).",
        steps: ["Biezpienu, olas, medu, miltus un sāli samaisa.", "Pannu viegli iesmērē ar olīveļļu.", "Cep plācenīšus 2–3 min katrā pusē.", "Pusi atliek 2. dienas brokastīm. Pasniedz ar ogām un jogurtu."] },
    ],
  },
  {
    n: 2,
    batch: "Brokastīs ēd vakar pagatavotos biezpiena plācenīšus.",
    meals: [
      { type: "brokastis", title: "Biezpiena plācenīši (no 1. dienas)", time: 3, from: "1/vakarinas", a: ["piens", "olas", "glutens"],
        ing: "Vakar pagatavotie plācenīši, 50 g svaigas ogas, 15 g grieķu jogurts (0 %).",
        steps: ["Plācenīšus uzsilda, pasniedz ar ogām un jogurtu."] },
      { type: "otras", title: "Salāti ar vārītu olu", time: 12, a: ["olas", "seklas"],
        ing: "50 g spināti, 50 g rukola, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 7 g saulespuķu sēklas, 5 g olīveļļa, 1 ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus saplūc un sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū pusē griezta ola."] },
      { type: "pusdienas", title: "Lēcas ar tvaicētiem dārzeņiem", time: 30, a: [],
        ing: "130 g lēcas, 50 g ziedkāposts, 50 g cukīni, 30 g burkāni, 30 g paprika, 5 g olīveļļa, šķipsniņa sāls.",
        steps: ["Lēcas novāra (~20 min).", "Ziedkāpostu, cukīni, burkānu un papriku tvaicē 8–10 min.", "Sajauc, pārlej ar olīveļļu, sāli pievieno gatavam."] },
      { type: "launags", title: "Augļi ar biezpienu", time: 3, a: ["piens"],
        ing: "1 ābols, 80 g biezpiens (0,5 %).",
        steps: ["Augļus sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Baltā zivs ar dārzeņiem", time: 30, a: ["zivs"],
        ing: "110 g baltās zivs fileja, 100 g kartupeļi, 50 g burkāni, 50 g paprika, 50 g cukīni, 50 g ziedkāposts, 5 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs, pipari.", "Cep 20–25 min, sāli pievieno gatavam."] },
    ],
  },
  {
    n: 3,
    batch: "Pusdienās gatavo pupiņu sautējumu (2 porcijas) un vakarā krēmzupu (2 porcijas) — pusi katram atstāj 4. dienai.",
    meals: [
      { type: "brokastis", title: "Omlete ar dārzeņiem", time: 12, a: ["olas", "piens"],
        ing: "1 ola, 2 olu baltumi, 5 g olīveļļa, 30 g spināti, 30 g šampinjoni, 10 g sīpoli, 20 g liess siers (10 %).",
        steps: ["Olu un olu baltumus sakuļ kopā.", "Olīveļļā uz pannas ielej olu masu.", "Virsū spinātus, šampinjonus, sīpolu un sieru.", "Cep zem vāka 4–5 min."] },
      { type: "otras", title: "Burkānu salāti ar maizi un kefīru", time: 8, a: ["piens", "glutens", "seklas"],
        ing: "100 g rīvēti burkāni, 5 g olīveļļa, 5 g ķirbju sēklas, 70 g rupjmaize, 120 ml kefīrs (2,5 %).",
        steps: ["Burkānus sarīvē, pievieno olīveļļu un ķirbju sēklas, pasniedz ar maizes šķēli un glāzi kefīra."] },
      { type: "pusdienas", title: "Pupiņu sautējums ar tofu", time: 25, portions: 2, a: ["soja"],
        ing: "200 g vārītas pupiņas, 50 g spināti, 50 g tomāti, 50 g šampinjoni, 150 g tofu, 30 g sīpoli, 5 g olīveļļa, pētersīļi, pipari, sāls.",
        steps: ["Sīpolu apcep olīveļļā.", "Pievieno šampinjonus, tomātus un spinātus.", "Pievieno pupiņas un tofu.", "Sautē 15 min, piedevā garšvielas. Pusi atliek 4. dienai."] },
      { type: "launags", title: "Rīsu galetes ar biezpienu un greipfrūtu", time: 4, a: ["rieksti", "piens"],
        ing: "2 pilngraudu rīsu galetes, 10 g zemesriekstu sviests, 60 g biezpiens (0,5 %), ½ greipfrūts, ½ banāns.",
        steps: ["Galetes apziež ar zemesriekstu sviestu un biezpienu.", "Greipfrūts un banāns."] },
      { type: "vakarinas", title: "Ķirbja krēmzupa ar lēcām", time: 30, portions: 2, a: ["piens"],
        ing: "200 g ķirbis, 60 g sīpoli, 10 g ķiploki, 80 g burkāni, 220 g kartupeļi, 80 g sarkanās lēcas, 20 g kausētais siers (Dzintars Light, 7,5 %), paprika, pipari, sāls.",
        serve: "5 g ķirbju sēklas.",
        steps: ["Sīpolu un ķiploku apcep.", "Pievieno ķirbi, burkānu, kartupeli un ūdeni.", "Vāra ~20 min, līdz mīksts.", "Sarkanās lēcas izskalo un pievieno kopā ar dārzeņiem — tās izvārās mīkstas un sablenderējas gludi.", "Pievieno kausēto sieru, sablenderē.", "Katrai porcijai virsū 5 g ķirbju sēklu. Pusi zupas atliek 4. dienai."] },
    ],
  },
  {
    n: 4,
    batch: "Ēd vakar gatavoto pupiņu sautējumu un krēmzupu.",
    meals: [
      { type: "brokastis", title: "Griķu pārslu putra ar biezpienu", time: 8, a: ["piens", "rieksti"],
        ing: "60 g griķu pārslas, 100 ml vājpiens (0,5 %), 70 g biezpiens (0,5 %), 7 g zemesriekstu sviests.",
        steps: ["Griķu pārslas aplej ar karstu vājpienu vai īsi pavāra, pievieno biezpienu un zemesriekstu sviestu."] },
      { type: "otras", title: "Pupiņu sautējums (no 3. dienas) ar kefīru", time: 3, from: "3/pusdienas", a: ["soja", "piens"],
        ing: "200 ml kefīrs (2,5 %).",
        steps: ["Sautējumu uzsilda, pasniedz ar glāzi kefīra."] },
      { type: "pusdienas", title: "Ķirbja krēmzupa (no 3. dienas)", time: 3, from: "3/vakarinas", a: ["piens"],
        ing: "Vakar gatavotā krēmzupa, 5 g ķirbju sēklas.",
        steps: ["Zupu uzsilda, virsū uzkaisa 5 g ķirbju sēklu."] },
      { type: "launags", title: "Augļu salāti ar biezpienu", time: 5, a: ["piens"],
        ing: "1 kivi, ½ ābols, ½ banāns, 10 g medus, 60 g biezpiens (0,5 %).",
        steps: ["Augļus sagriež, sajauc ar biezpienu un medu."] },
      { type: "vakarinas", title: "Forele ar dārzeņiem", time: 30, a: ["zivs"],
        ing: "100 g foreles fileja, 50 g baklažāns, 50 g ziedkāposts, 50 g paprika, 90 g saldais kartupelis.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas.", "Virsū forele, sāls, pipari.", "Cep ~20 min."] },
    ],
  },
  {
    n: 5,
    batch: "Čia pudiņu vislabāk samaisīt jau iepriekšējā vakarā.",
    meals: [
      { type: "brokastis", title: "Čia pudiņš ar jogurtu un ogām", time: 5, a: ["piens", "seklas"],
        ing: "25 g čia sēklas, 100 ml vājpiens (0,5 %), 100 g grieķu jogurts (0 %), 10 g medus, 100 g svaigas ogas.",
        steps: ["Čia sēklas, vājpienu, jogurtu un medu samaisa.", "Ledusskapī vismaz 20 min, labāk visu nakti.", "Virsū svaigas ogas."] },
      { type: "otras", title: "Banāns ar biezpienu un šokolādi", time: 3, a: ["piens"],
        ing: "1 banāns, 60 g biezpiens (0,5 %), 2 gabaliņi tumšās šokolādes.",
        steps: ["Banānu sagriež un sajauc ar biezpienu, šokolādi sarīvē virsū."] },
      { type: "pusdienas", title: "Grūbas ar vistu un dārzeņiem", time: 40, a: ["glutens"],
        ing: "85 g grūbas, 80 g vistas fileja, 30 g burkāni, 30 g paprika, 30 g šampinjoni, 30 g cukīni, 20 g sīpoli, 5 g ķiploki, dilles, pētersīļi, 5 g olīveļļa, pipari, sāls.",
        steps: ["Grūbas novāra (~30–40 min).", "Vistu sagriež un apcep olīveļļā.", "Pievieno dārzeņus un apcep.", "Sajauc grūbas ar vistu, dārzeņiem un garšvielām."] },
      { type: "launags", title: "Augļu salāti ar biezpienu", time: 5, a: ["piens"],
        ing: "½ banāns, 1 kivi, 60 g biezpiens (0,5 %).",
        steps: ["Augļus sagriež, sajauc ar biezpienu."] },
      { type: "vakarinas", title: "Salāti ar tītara fileju", time: 25, a: ["glutens"],
        ing: "60 g kalē kāposts, 30 g paprika, 30 g tomāti, 30 g gurķi, 100 g cepta tītara fileja, 40 g rupjmaize, 5 g olīveļļa, baziliks, pipari, sāls.",
        steps: ["Tītara fileju cep krāsnī vai uz pannas.", "Kāli, papriku, tomātu un gurķi sagriež.", "Sajauc, pārlej ar olīveļļu, virsū tītars."] },
    ],
  },
  {
    n: 6,
    batch: "Šodien jaunas receptes — nekas no iepriekšējās dienas.",
    meals: [
      { type: "brokastis", title: "Smūtija bļoda ar jogurtu", time: 8, a: ["piens", "rieksti", "glutens"],
        ing: "1 banāns, 30 g svaigas ogas, 40 ml vājpiens (0,5 %), 100 g grieķu jogurts (0 %), 40 g spināti, 8 g rieksti, 70 g auzu pārslas.",
        steps: ["Banānu, ogas, vājpienu, jogurtu un spinātus sablenderē, ielej bļodā, virsū rieksti un grauzdētas auzu pārslas."] },
      { type: "otras", title: "Pilngraudu tortiljas pica", time: 12, a: ["glutens", "piens"],
        ing: "1 pilngraudu tortilja, 12 g pesto, 20 g spināti, 30 g tomāti, 20 g sīpoli, 20 g šampinjoni, 35 g liess siers (10 %).",
        steps: ["Tortilju apziež ar pesto.", "Virsū spinātus, tomātus, sīpolu, šampinjonus un sieru.", "Cep 200°C 8–10 min."] },
      { type: "pusdienas", title: "Salāti ar vistas fileju", time: 25, a: [],
        ing: "60 g kalē kāposts, 30 g paprika, 30 g tomāti, 30 g gurķi, 100 g cepta vistas fileja, 5 g olīveļļa, baziliks, pipari, sāls.",
        steps: ["Vistas fileju cep krāsnī vai uz pannas.", "Dārzeņus sagriež.", "Sajauc, pārlej ar olīveļļu, virsū vista."] },
      { type: "launags", title: "Rīsu galetes ar biezpienu un persiku", time: 4, a: ["rieksti", "piens"],
        ing: "2 rīsu galetes, 10 g zemesriekstu sviests, 40 g biezpiens (0,5 %), 1 persiks.",
        steps: ["Galetes apziež ar zemesriekstu sviestu un biezpienu.", "Persiks."] },
      { type: "vakarinas", title: "Baltā zivs ar dārzeņiem", time: 30, a: ["zivs"],
        ing: "100 g baltās zivs fileja, 100 g kartupeļi, 50 g baklažāns, 50 g paprika, 50 g cukīni, 50 g Briseles kāposti, 5 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Dārzeņus sagriež, liek uz pannas, pārlej olīveļļu.", "Virsū zivs un pipari.", "Cep 20–25 min."] },
    ],
  },
  {
    n: 7,
    batch: "Vakariņās gatavo 2 pildītas paprikas — vienu atstāj 8. dienas launagam.",
    meals: [
      { type: "brokastis", title: "Muslis ar jogurtu un ogām", time: 3, a: ["piens", "glutens", "rieksti"],
        ing: "60 g muslis, ½ banāns, 100 g grieķu jogurts (0 %), 100 g svaigas ogas.",
        steps: ["Musli liek bļodā, virsū jogurts, sagriezts banāns un ogas."] },
      { type: "otras", title: "Salāti ar vārītu olu", time: 12, a: ["olas", "seklas"],
        ing: "50 g romiešu salāti, 50 g spināti, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 7 g saulespuķu sēklas, 5 g olīveļļa, 1 ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū ola."] },
      { type: "pusdienas", title: "Lēcas ar sautētiem dārzeņiem", time: 30, a: [],
        ing: "100 g lēcas, 30 g brokolis, 40 g burkāni, 40 g kālis, 30 g šampinjoni, 5 g olīveļļa.",
        steps: ["Lēcas novāra (~20 min).", "Dārzeņus sautē olīveļļā 8–10 min.", "Sajauc kopā."] },
      { type: "launags", title: "Apelsīns ar biezpienu", time: 3, a: ["piens"],
        ing: "1 apelsīns, ½ banāns, 100 g biezpiens (0,5 %).",
        steps: ["Apelsīnu sagriež, pasniedz ar biezpienu."] },
      { type: "vakarinas", title: "Pildīta paprika ar vistu", time: 40, portions: 2, a: ["piens"],
        ing: "2 paprikas, 180 g vārīti brūnie rīsi, 120 g vistas fileja, 20 g sīpoli, 40 g burkāni, 40 g cukīni, 40 g tomāti, 5 g ķiploki, pētersīļi, dilles, 5 g olīveļļa, pipari, sāls.",
        serve: "10 g krējums (12–15 %).",
        steps: ["Rīsus novāra.", "Vistas fileju sagriež gabaliņos un apcep ar dārzeņiem olīveļļā.", "Sajauc ar rīsiem un garšvielām.", "Papriku pilda un cep 200°C 25–30 min.", "Katrai paprikai virsū 10 g krējuma. Vienu atstāj 8. dienai."] },
    ],
  },
  {
    n: 8,
    batch: "Launagā ēd vakar gatavoto pildīto papriku.",
    meals: [
      { type: "brokastis", title: "Griķu pārslu putra ar biezpienu", time: 8, a: ["piens"],
        ing: "60 g griķu pārslas, 100 ml vājpiens (0,5 %), 60 g biezpiens (0,5 %), zaļumi, 20 g tomāti.",
        steps: ["Griķu pārslas aplej ar karstu vājpienu, pasniedz ar biezpienu, zaļumiem un tomātiem."] },
      { type: "otras", title: "Tortilja ar pupiņām", time: 10, a: ["glutens", "piens", "soja"],
        ing: "1 pilngraudu tortilja, 100 g vārītas pupiņas, 20 g šampinjoni, sauja spinātu, 20 g liess siers (10 %).",
        steps: ["Tortilju pilda ar pupiņām, šampinjoniem un spinātiem.", "Pārkaisa ar sieru.", "Saloka un uzsilda uz pannas."] },
      { type: "pusdienas", title: "Vista ar dārzeņiem", time: 30, a: [],
        ing: "80 g vistas fileja, 120 g saldais kartupelis, 50 g kālis, 30 g paprika, 30 g burkāni, 5 g olīveļļa, sāls, pipari.",
        steps: ["Cepeškrāsni uzsilda līdz 200°C.", "Vistu un dārzeņus liek uz pannas, pārlej olīveļļu.", "Cep ~25 min."] },
      { type: "launags", title: "Pildīta paprika (no 7. dienas)", time: 3, from: "7/vakarinas", a: ["piens"],
        ing: "Vakar gatavotā pildītā paprika, 10 g krējums (12–15 %).",
        steps: ["Papriku uzsilda, virsū 10 g krējuma."] },
      { type: "vakarinas", title: "Salāti ar garnelēm", time: 12, a: ["juras", "glutens"],
        ing: "60 g rukola, 30 g tomāti, 30 g gurķi, 30 g avokado, 30 g paprika, 100 g garneles, 40 g rupjmaize, baziliks, 5 g olīveļļa.",
        steps: ["Garneles apcep olīveļļā 3–4 min.", "Dārzeņus un avokado sagriež.", "Sajauc, virsū garneles un baziliks."] },
    ],
  },
  {
    n: 9,
    batch: "Pusdienās gatavo laša zupu (2 porcijas) un vakarā vistas sautējumu — pusi katram atstāj 10. dienai.",
    meals: [
      { type: "brokastis", title: "Auzu pārslu putra ar olu baltumiem", time: 12, a: ["piens", "glutens", "olas", "rieksti"],
        ing: "60 g pilngraudu auzu pārslas, 100 ml vājpiens (0,5 %), 2 olu baltumi, 15 g ievārījums, 7 g zemesriekstu sviests.",
        steps: ["Auzu pārslas ar vājpienu pavāra 5–7 min.", "Olu baltumus sakuļ un ievieš putrā pēdējā minūtē, ātri maisot.", "Dzeltenumus noglabā ledusskapī un izmanto omletei vai mērcei.", "Virsū ievārījums un zemesriekstu sviests."] },
      { type: "otras", title: "Salāti ar vārītu olu", time: 12, a: ["olas", "seklas"],
        ing: "50 g romiešu salāti, 50 g spināti, 30 g gurķi, 30 g tomāti, 20 g sēklu dīgsti, 30 g paprika, 7 g saulespuķu sēklas, 5 g olīveļļa, 1 ola.",
        steps: ["Olu novāra 8 min.", "Lapas un dārzeņus sagriež.", "Pievieno dīgstus un sēklas.", "Pārlej ar olīveļļu, virsū ola."] },
      { type: "pusdienas", title: "Laša zupa", time: 30, portions: 2, a: ["zivs"],
        ing: "170 g laša fileja, 280 g kartupeļi, 100 g burkāni, 60 g sīpoli, 20 g zivju mērce, 100 g šampinjoni, 40 g selerija, zaļumi.",
        steps: ["Kartupeli, burkānu, sīpolu un seleriju vāra ūdenī.", "Pievieno šampinjonus un sagrieztu lasi.", "Pievieno zivju mērci un zaļumus.", "Vāra ~10 min. Pusi atliek 10. dienai."] },
      { type: "launags", title: "Augļu salāti ar biezpienu", time: 5, a: ["piens"],
        ing: "1 kivi, ½ mango, ½ banāns, 60 g biezpiens (0,5 %).",
        steps: ["Augļus sagriež, sajauc ar biezpienu."] },
      { type: "vakarinas", title: "Vistas gaļas sautējums", time: 35, portions: 2, a: [],
        ing: "190 g liesa vistas gaļa, 320 g kartupeļi, 100 g cukīni, 100 g ziedkāposts, 100 g burkāni, 7 g olīveļļa, 20 g sīpoli, 5 g ķiploki, sāls, pipari.",
        steps: ["Vistu apcep olīveļļā.", "Pievieno sīpolu, ķiploku un dārzeņus.", "Sautē ~20 min. Pusi atliek 10. dienai."] },
    ],
  },
  {
    n: 10,
    batch: "Ēd vakar gatavoto vistas sautējumu un laša zupu.",
    meals: [
      { type: "brokastis", title: "Rupjmaize ar biezpienu un avokado", time: 7, a: ["piens", "glutens"],
        ing: "60 g rupjmaize, 50 g biezpiens (0,5 %), 40 g grieķu jogurts (0 %), dilles, pētersīļi, 30 g avokado.",
        steps: ["Biezpienu sajauc ar jogurtu un zaļumiem, uzziež uz maizes, virsū sagriezts avokado."] },
      { type: "otras", title: "Vistas sautējums (no 9. dienas)", time: 3, from: "9/vakarinas", a: [],
        ing: "Vakar gatavotais vistas gaļas sautējums.",
        steps: ["Sautējumu uzsilda un apēd."] },
      { type: "pusdienas", title: "Laša zupa (no 9. dienas) ar maizi", time: 5, from: "9/pusdienas", a: ["zivs", "glutens"],
        ing: "60 g rupjmaize.",
        steps: ["Zupu uzsilda, pasniedz ar maizes šķēli."] },
      { type: "launags", title: "Biešu salāti ar olu un biezpienu", time: 4, a: ["olas", "piens"],
        ing: "100 g vārītas bietes, 40 g biezpiens (0,5 %), ½ ābols, 1 ola.",
        steps: ["Bietes sarīvē un sajauc ar biezpienu, pasniedz ar pusē grieztu olu."] },
      { type: "vakarinas", title: "Salāti ar garnelēm", time: 12, a: ["juras", "glutens"],
        ing: "60 g spināti, 30 g tomāti, 30 g gurķi, 30 g paprika, 100 g garneles, 30 g rupjmaize, baziliks, 5 g olīveļļa.",
        steps: ["Garneles apcep olīveļļā 3–4 min.", "Dārzeņus sagriež.", "Sajauc, virsū garneles un baziliks."] },
    ],
  },
];

// ---- IEPIRKUMU DATI ----
// Saraksts vairs netiek rakstīts ar roku: to saskaita `uzturvertibas.mjs` no to pašu
// recepšu sastāvdaļām. Ja maina recepti, saraksts mainās pats un nevar aiziet malā.

// Produktu katalogs: kategorija + iepakojuma ieteikums
export const catalog = {
  "Pilngraudu auzu pārslas": ["Graudi un putraimi", "1 paka (500 g)"],
  "Griķu pārslas": ["Graudi un putraimi", "1 paka (400–500 g)"],
  "Kuskuss": ["Graudi un putraimi", "1 paka"],
  "Grūbas": ["Graudi un putraimi", "1 paka"],
  "Brūnie rīsi": ["Graudi un putraimi", "1 paka"],
  "Muslis": ["Graudi un putraimi", "1 maza paka"],
  "Lēcas": ["Graudi un putraimi", "1 paka"],
  "Sarkanās lēcas": ["Graudi un putraimi", "1 maza paka"],
  "Vārītas pupiņas": ["Graudi un putraimi", "2 bundžas vai 1 paka sausu"],
  "Čia sēklas": ["Graudi un putraimi", "1 maza paka"],
  "Rīsu milti": ["Graudi un putraimi", "1 maza paka"],
  "Rupjmaize": ["Maize", "kvalitatīva, mazāk sāls"],
  "Rīsu galetes": ["Maize", "1 paka"],
  "Pilngraudu tortilja": ["Maize", "1 paka"],
  "Vājpiens": ["Piena produkti", "1 l (0,5 %)"],
  "Biezpiens": ["Piena produkti", "~1 kg (0,5 %)"],
  "Grieķu jogurts": ["Piena produkti", "~400 g (0 %)"],
  "Kefīrs": ["Piena produkti", "0,5 l (2,5 %)"],
  "Liess siers": ["Piena produkti", "1 gabals (10 %)"],
  "Kausētais siers": ["Piena produkti", "Dzintars Light (7,5 %)"],
  "Krējums": ["Piena produkti", "1 maza paka (12–15 %)"],
  "Olas": ["Olas", "~15 gab"],
  "Tofu": ["Olbaltums", "1 paka"],
  "Vistas fileja": ["Gaļa un zivs", "~800 g"],
  "Tītara fileja": ["Gaļa un zivs", "~100 g"],
  "Baltā zivs": ["Gaļa un zivs", "~200 g (heks/menca)"],
  "Forele": ["Gaļa un zivs", "~100 g"],
  "Lasis": ["Gaļa un zivs", "~200 g"],
  "Garneles": ["Gaļa un zivs", "~200 g"],
  "Spināti": ["Dārzeņi un zaļumi", "2 pakas"],
  "Rukola": ["Dārzeņi un zaļumi", "1 paka"],
  "Romiešu salāti": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Kalē kāposts": ["Dārzeņi un zaļumi", "1 sauja"],
  "Gurķi": ["Dārzeņi un zaļumi", "1–2 gab"],
  "Tomāti": ["Dārzeņi un zaļumi", "~400 g"],
  "Paprika": ["Dārzeņi un zaļumi", "~5–6 gab"],
  "Burkāni": ["Dārzeņi un zaļumi", "~600 g"],
  "Cukīni": ["Dārzeņi un zaļumi", "1–2 gab"],
  "Ziedkāposts": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Brokolis": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Briseles kāposti": ["Dārzeņi un zaļumi", "1 maza paka"],
  "Baklažāns": ["Dārzeņi un zaļumi", "1 gab"],
  "Šampinjoni": ["Dārzeņi un zaļumi", "1 paka"],
  "Sīpoli": ["Dārzeņi un zaļumi", "~3 gab"],
  "Ķiploki": ["Dārzeņi un zaļumi", "1 galviņa"],
  "Ķirbis": ["Dārzeņi un zaļumi", "1 gabals"],
  "Kartupeļi": ["Dārzeņi un zaļumi", "~1 kg"],
  "Saldais kartupelis": ["Dārzeņi un zaļumi", "1 gab"],
  "Kālis (kolrābis)": ["Dārzeņi un zaļumi", "1 gab"],
  "Bietes": ["Dārzeņi un zaļumi", "1 vārīta biete"],
  "Sēklu dīgsti": ["Dārzeņi un zaļumi", "1 maza paka"],
  "Avokado": ["Dārzeņi un zaļumi", "1–2 gab"],
  "Selerija": ["Dārzeņi un zaļumi", "1 kāts"],
  "Zaļumi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Dilles": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Pētersīļi": ["Dārzeņi un zaļumi", "1 saišķis"],
  "Baziliks": ["Dārzeņi un zaļumi", "1 podiņš"],
  "Ābols": ["Augļi", "~3 gab"],
  "Apelsīns": ["Augļi", "~2 gab"],
  "Banāns": ["Augļi", "~5 gab"],
  "Kivi": ["Augļi", "~3 gab"],
  "Persiki": ["Augļi", "1 gab"],
  "Mango": ["Augļi", "1 gab (pietiek puse)"],
  "Greipfrūts": ["Augļi", "1 gab (pietiek puse)"],
  "Svaigas ogas": ["Augļi", "~500 g (var saldētas)"],
  "Zemesriekstu sviests": ["Rieksti un sēklas", "1 burka"],
  "Rieksti (mandeles, valrieksti)": ["Rieksti un sēklas", "1 maza paka"],
  "Saulespuķu sēklas": ["Rieksti un sēklas", "1 maza paka"],
  "Ķirbju sēklas": ["Rieksti un sēklas", "1 maza paka"],
  "Olīveļļa": ["Eļļas, garšvielas, citi", "Extra Virgin, 1 pudele"],
  "Medus": ["Eļļas, garšvielas, citi", "1 burka"],
  "Pesto": ["Eļļas, garšvielas, citi", "1 maza burka"],
  "Ievārījums": ["Eļļas, garšvielas, citi", "1 burka"],
  "Zivju mērce": ["Eļļas, garšvielas, citi", "1 pudelīte"],
  "Tumšā šokolāde": ["Eļļas, garšvielas, citi", "1 tāfelīte (≥70%)"],
};



// Produkti, kas labi stāv 10 dienas -> pērc VIENREIZ pirmajā iepirkumā.
// Viss pārējais ir ātrbojīgs un tiek dalīts starp diviem iepirkumiem.
// Robežgadījumos (paprika, cukīni, brokolis) apzināti izvēlēts ātrbojīgais grozs —
// labāk svaigāks produkts nekā par vienu iepirkuma reizi mazāk.
export const pantry = new Set([
  // sausā bakaleja
  "Pilngraudu auzu pārslas", "Griķu pārslas", "Kuskuss", "Grūbas", "Brūnie rīsi",
  "Muslis", "Lēcas", "Sarkanās lēcas", "Vārītas pupiņas", "Čia sēklas", "Rīsu milti",
  "Rīsu galetes", "Pilngraudu tortilja",
  // rieksti, sēklas, eļļas, garšvielas
  "Zemesriekstu sviests", "Rieksti (mandeles, valrieksti)", "Saulespuķu sēklas", "Ķirbju sēklas",
  "Olīveļļa", "Medus", "Pesto", "Ievārījums", "Zivju mērce", "Tumšā šokolāde",
  // ilgi stāvoši dārzeņi un augļi
  "Burkāni", "Sīpoli", "Ķiploki", "Ķirbis", "Kartupeļi", "Saldais kartupelis",
  "Kālis (kolrābis)", "Bietes", "Ābols", "Apelsīns", "Greipfrūts", "Kivi", "Mango",
  // olas
  "Olas",
]);
